// Romaji reading exercise. s = sentence with furigana markup, k = hiragana reading split into words
// (particles は/へ/を are their own tokens), en = translation, d = difficulty.
window.ROMAJI_SENTENCES = [
  { id: "r01", d: 1, s: "わたしは{学生|がくせい}です。", k: "わたし は がくせい です", en: "I am a student." },
  { id: "r02", d: 1, s: "{水|みず}をください。", k: "みず を ください", en: "Water, please." },
  { id: "r03", d: 1, s: "これは{本|ほん}です。", k: "これ は ほん です", en: "This is a book." },
  { id: "r04", d: 1, s: "{私|わたし}は{日本人|にほんじん}です。", k: "わたし は にほんじん です", en: "I am Japanese." },
  { id: "r05", d: 1, s: "{毎日|まいにち}{学校|がっこう}へ{行|い}きます。", k: "まいにち がっこう へ いきます", en: "I go to school every day." },
  { id: "r06", d: 1, s: "{朝|あさ}ごはんを{食|た}べます。", k: "あさごはん を たべます", en: "I eat breakfast." },
  { id: "r07", d: 1, s: "{先生|せんせい}は{親切|しんせつ}です。", k: "せんせい は しんせつ です", en: "The teacher is kind." },
  { id: "r08", d: 1, s: "{駅|えき}はどこですか。", k: "えき は どこ です か", en: "Where is the station?" },
  { id: "r09", d: 2, s: "{今日|きょう}は{天気|てんき}がいいです。", k: "きょう は てんき が いい です", en: "The weather is nice today." },
  { id: "r10", d: 2, s: "{図書館|としょかん}で{本|ほん}を{読|よ}みます。", k: "としょかん で ほん を よみます", en: "I read books at the library." },
  { id: "r11", d: 2, s: "{友達|ともだち}と{映画|えいが}を{見|み}ました。", k: "ともだち と えいが を みました", en: "I watched a movie with a friend." },
  { id: "r12", d: 2, s: "{七時|しちじ}に{起|お}きます。", k: "しちじ に おきます", en: "I get up at seven o'clock." },
  { id: "r13", d: 2, s: "{日本語|にほんご}は{難|むずか}しいですが、おもしろいです。", k: "にほんご は むずかしい です が おもしろい です", en: "Japanese is difficult, but it's interesting." },
  { id: "r14", d: 2, s: "{東京|とうきょう}は{大|おお}きいです。", k: "とうきょう は おおきい です", en: "Tokyo is big." },
  { id: "r15", d: 2, s: "{電車|でんしゃ}で{会社|かいしゃ}へ{行|い}きます。", k: "でんしゃ で かいしゃ へ いきます", en: "I go to the office by train." },
  { id: "r16", d: 2, s: "{昨日|きのう}は{雨|あめ}が{降|ふ}りました。", k: "きのう は あめ が ふりました", en: "It rained yesterday." },
  { id: "r17", d: 2, s: "コーヒーを{飲|の}みませんか。", k: "こーひー を のみませんか", en: "Would you like to drink some coffee?" },
  { id: "r18", d: 3, s: "{明日|あした}は{友達|ともだち}と{買|か}い{物|もの}に{行|い}きます。", k: "あした は ともだち と かいもの に いきます", en: "Tomorrow I'm going shopping with a friend." },
  { id: "r19", d: 3, s: "{毎朝|まいあさ}{六時|ろくじ}に{起|お}きて、{散歩|さんぽ}をします。", k: "まいあさ ろくじ に おきて さんぽ を します", en: "Every morning I get up at six and take a walk." },
  { id: "r20", d: 3, s: "{窓|まど}を{開|あ}けてください。", k: "まど を あけて ください", en: "Please open the window." },
  { id: "r21", d: 3, s: "{私|わたし}の{家|いえ}は{駅|えき}から{近|ちか}いです。", k: "わたし の いえ は えき から ちかい です", en: "My house is close to the station." },
  { id: "r22", d: 3, s: "{日曜日|にちようび}は{会社|かいしゃ}へ{行|い}きません。", k: "にちようび は かいしゃ へ いきません", en: "I don't go to the office on Sundays." },
  { id: "r23", d: 3, s: "{部屋|へや}にだれもいません。", k: "へや に だれ も いません", en: "There is nobody in the room." },
  { id: "r24", d: 3, s: "{東京|とうきょう}は{大阪|おおさか}より{大|おお}きいです。", k: "とうきょう は おおさか より おおきい です", en: "Tokyo is bigger than Osaka." },
  { id: "r25", d: 3, s: "{一緒|いっしょ}に{昼|ひる}ごはんを{食|た}べましょう。", k: "いっしょ に ひるごはん を たべましょう", en: "Let's eat lunch together." },
  { id: "r101", d: 1, s: "わたしはコーヒーが{好|す}きです。", k: "わたし は こーひー が すき です", en: "I like coffee." },
  { id: "r102", d: 1, s: "{今日|きょう}は{月曜日|げつようび}です。", k: "きょう は げつようび です", en: "Today is Monday." },
  { id: "r103", d: 1, s: "{毎朝|まいあさ}{七時|しちじ}に{起|お}きます。", k: "まいあさ しちじ に おきます", en: "I get up at seven every morning." },
  { id: "r104", d: 1, s: "これは{私|わたし}のかばんです。", k: "これ は わたし の かばん です", en: "This is my bag." },
  { id: "r105", d: 1, s: "{駅|えき}で{電車|でんしゃ}を{待|ま}ちます。", k: "えき で でんしゃ を まちます", en: "I wait for the train at the station." },
  { id: "r106", d: 1, s: "{水|みず}を{飲|の}みたいです。", k: "みず を のみたい です", en: "I want to drink water." },
  { id: "r107", d: 1, s: "{日本語|にほんご}を{勉強|べんきょう}しています。", k: "にほんご を べんきょう して います", en: "I am studying Japanese." },
  { id: "r108", d: 2, s: "{図書館|としょかん}に{本|ほん}があります。", k: "としょかん に ほん が あります", en: "There are books in the library." },
  { id: "r109", d: 2, s: "{公園|こうえん}に{子|こ}どもがいます。", k: "こうえん に こども が います", en: "There are children in the park." },
  { id: "r110", d: 2, s: "{昨日|きのう}、{友達|ともだち}に{会|あ}いました。", k: "きのう ともだち に あいました", en: "I met a friend yesterday." },
  { id: "r111", d: 2, s: "{毎晩|まいばん}{十時|じゅうじ}に{寝|ね}ます。", k: "まいばん じゅうじ に ねます", en: "I go to bed at ten every night." },
  { id: "r112", d: 2, s: "{私|わたし}の{家|いえ}は{駅|えき}の{近|ちか}くです。", k: "わたし の いえ は えき の ちかく です", en: "My house is near the station." },
  { id: "r113", d: 2, s: "{今|いま}、{何時|なんじ}ですか。", k: "いま なんじ です か", en: "What time is it now?" },
  { id: "r114", d: 2, s: "{手|て}を{洗|あら}ってから、ごはんを{食|た}べます。", k: "て を あらって から ごはん を たべます", en: "I wash my hands and then eat." },
  { id: "r115", d: 2, s: "{去年|きょねん}、{日本|にほん}へ{行|い}きました。", k: "きょねん にほん へ いきました", en: "I went to Japan last year." },
  { id: "r116", d: 3, s: "{私|わたし}は{肉|にく}をあまり{食|た}べません。", k: "わたし は にく を あまり たべません", en: "I don't eat meat very often." },
  { id: "r117", d: 3, s: "{来週|らいしゅう}の{土曜日|どようび}に{友達|ともだち}と{映画|えいが}を{見|み}に{行|い}きます。", k: "らいしゅう の どようび に ともだち と えいが を み に いきます", en: "Next Saturday I'm going to see a movie with a friend." },
  { id: "r118", d: 3, s: "{日本語|にほんご}の{先生|せんせい}はとても{親切|しんせつ}です。", k: "にほんご の せんせい は とても しんせつ です", en: "The Japanese teacher is very kind." },
  { id: "r119", d: 3, s: "{夏|なつ}は{暑|あつ}くて、{冬|ふゆ}は{寒|さむ}いです。", k: "なつ は あつくて ふゆ は さむい です", en: "Summer is hot and winter is cold." },
  { id: "r120", d: 3, s: "ここでたばこを{吸|す}わないでください。", k: "ここ で たばこ を すわないで ください", en: "Please don't smoke here." },
  { id: "r121", d: 3, s: "{私|わたし}は{妹|いもうと}と{二人|ふたり}で{住|す}んでいます。", k: "わたし は いもうと と ふたり で すんで います", en: "I live with my younger sister (the two of us)." },
  { id: "r122", d: 3, s: "このりんごはいくらですか。", k: "この りんご は いくら です か", en: "How much is this apple?" },
  { id: "r123", d: 3, s: "{駅|えき}まで{歩|ある}いて{十分|じゅっぷん}です。", k: "えき まで あるいて じゅっぷん です", en: "It's a ten-minute walk to the station." },
  { id: "r124", d: 3, s: "{田中|たなか}さんは{会社|かいしゃ}の{人|ひと}です。", k: "たなか さん は かいしゃ の ひと です", en: "Mr. Tanaka is a company employee." },
  { id: "r125", d: 3, s: "{写真|しゃしん}を{撮|と}ってもいいですか。", k: "しゃしん を とっても いい です か", en: "May I take a photo?" }
];
