// Hand-written N4 questions. Row format: [id, difficulty, question, [correct, wrong, wrong, wrong], English, note]
// Markup: {漢字|かんじ} = furigana, ＿＿ = blank. The correct answer is listed first; the app shuffles the choices.
(function () {
  window.QUESTIONS = window.QUESTIONS || [];
  const add = (t, rows) => rows.forEach(([id, d, q, c, en, note]) => window.QUESTIONS.push({ id: "n4" + t + id, lv: 4, t, d, q, c, a: 0, en, note }));

  // ---------- Grammar ----------
  add("g", [
    ["01", 1, "{私|わたし}は{富士山|ふじさん}に{登|のぼ}った＿＿があります。", ["こと", "の", "もの", "ところ"], "I have climbed Mt. Fuji.", "Past plain form + ことがある = have done … before (experience)."],
    ["02", 1, "{私|わたし}は{納豆|なっとう}を{食|た}べた＿＿がありません。", ["こと", "の", "もの", "ほう"], "I have never eaten natto.", "〜たことがない = have never done …."],
    ["03", 1, "{風邪|かぜ}をひいたら、{早|はや}く{寝|ね}た＿＿がいいです。", ["ほう", "こと", "もの", "ところ"], "If you catch a cold, you should go to bed early.", "た-form + ほうがいい = it's better to … (advice)."],
    ["04", 2, "{明日|あした}は{早|はや}く{起|お}き＿＿なりません。", ["なければ", "なくて", "ないで", "なかったら"], "I have to get up early tomorrow.", "ない-form (drop い) + ければなりません = must / have to."],
    ["05", 2, "{明日|あした}は{会社|かいしゃ}に{来|こ}＿＿もいいです。", ["なくても", "なくて", "なければ", "ないと"], "You don't have to come to the office tomorrow.", "ない-form (drop い) + くてもいい = don't have to."],
    ["06", 2, "{来年|らいねん}、{日本|にほん}へ{行|い}こう＿＿{思|おも}っています。", ["と", "に", "を", "が"], "I'm thinking of going to Japan next year.", "Volitional form (〜よう / 〜おう) + と思っています = I'm thinking of …."],
    ["07", 2, "{夏休|なつやす}みに{国|くに}へ{帰|かえ}る＿＿です。", ["つもり", "ながら", "まま", "ほど"], "I plan to go back to my country during summer vacation.", "Dictionary form + つもり = intend to …."],
    ["08", 3, "{田中|たなか}さんは{今日|きょう}{来|く}る＿＿です。{昨日|きのう}、そう{言|い}っていました。", ["はず", "ながら", "まま", "ほど"], "Mr. Tanaka should be coming today. He said so yesterday.", "〜はずだ = should be / is expected to (based on a reason)."],
    ["09", 3, "あの{人|ひと}は{頭|あたま}が{良|よ}＿＿ですね。", ["さそう", "いそう", "そう", "よそう"], "That person looks smart.", "い-adjective stem + そう = looks …. いい becomes よさそう."],
    ["10", 2, "{一生懸命|いっしょうけんめい}{勉強|べんきょう}した＿＿、{試験|しけん}に{落|お}ちました。", ["のに", "ので", "から", "ために"], "Even though I studied hard, I failed the exam.", "〜のに = although / even though (unexpected result)."],
    ["11", 2, "{安|やす}けれ＿＿、{買|か}います。", ["ば", "たら", "と", "なら"], "If it's cheap, I'll buy it.", "い-adjective: drop い + ければ = if …."],
    ["12", 2, "{雨|あめ}が{降|ふ}っ＿＿、{行|い}きません。", ["たら", "ば", "と", "なら"], "If it rains, I won't go.", "た-form + ら = if / when …."],
    ["13", 2, "このボタンを{押|お}す＿＿、ドアが{開|あ}きます。", ["と", "ば", "たら", "でも"], "When you press this button, the door opens.", "Dictionary form + と = whenever … happens, (natural result)."],
    ["14", 3, "A「{来週|らいしゅう}、{京都|きょうと}へ{行|い}きます。」\nB「{京都|きょうと}へ{行|い}く＿＿、この{店|みせ}がおすすめですよ。」", ["なら", "ば", "たら", "と"], "A: I'm going to Kyoto next week. B: If you're going to Kyoto, I recommend this shop.", "〜なら = if that's the case / if you're going to …."],
    ["15", 2, "{音楽|おんがく}を{聞|き}き＿＿{勉強|べんきょう}します。", ["ながら", "て", "たら", "ので"], "I study while listening to music.", "Stem + ながら = while doing …."],
    ["16", 2, "{電気|でんき}が＿＿います。{誰|だれ}もいないのに。", ["ついて", "つけて", "つき", "つける"], "The light is on. Even though nobody is here.", "{電気|でんき}がついている (intransitive: it's on) vs {電気|でんき}をつける (transitive: turn on)."],
    ["17", 3, "{大切|たいせつ}な{本|ほん}を{失|な}くして＿＿。", ["しまいました", "いきました", "おきました", "あげました"], "Oh no, I lost an important book.", "て-form + しまう = end up doing (often with regret)."],
    ["18", 2, "パーティーの{前|まえ}に、{飲|の}み{物|もの}を{買|か}って＿＿。", ["おきます", "おくます", "おきない", "おきて"], "Before the party, I'll buy drinks in advance.", "て-form + おく = do something in advance."],
    ["19", 2, "このケーキを{食|た}べて＿＿ください。", ["みて", "みる", "みた", "みよう"], "Please try eating this cake.", "て-form + みる = try doing …. 〜てみてください = please try …."],
    ["20", 3, "{友達|ともだち}が{私|わたし}に{本|ほん}を{貸|か}して＿＿。", ["くれました", "あげました", "もらいました", "さしあげました"], "A friend lent me a book.", "〜てくれる = someone does something for me."],
    ["21", 3, "{先生|せんせい}に＿＿。", ["ほめられました", "ほめれました", "ほめらせました", "ほめりました"], "I was praised by the teacher.", "Passive: ほめる → ほめられる (ichidan: drop る + られる)."],
    ["22", 3, "{私|わたし}は{日本語|にほんご}の{新聞|しんぶん}が{読|よ}め＿＿。", ["ます", "られます", "れます", "せます"], "I can read Japanese newspapers.", "Potential of godan verbs: 読む → 読める (u → eru)."],
    ["23", 3, "{私|わたし}は{納豆|なっとう}が{食|た}べ＿＿。", ["られます", "らせます", "られせます", "せます"], "I can eat natto.", "Potential of ichidan verbs: drop る + られる."],
    ["24", 2, "{天気予報|てんきよほう}によると、{明日|あした}は{雨|あめ}が{降|ふ}る＿＿。", ["そうです", "そうなです", "そうにです", "そうだです"], "According to the weather forecast, it will rain tomorrow.", "Plain form + そうです = I hear that … (hearsay)."],
    ["25", 2, "{日本語|にほんご}を{勉強|べんきょう}する＿＿、{日本|にほん}へ{行|い}きます。", ["ために", "ながら", "ばかり", "ほど"], "I'm going to Japan in order to study Japanese.", "Dictionary form + ために = in order to …."],
    ["26", 3, "{毎日|まいにち}{運動|うんどう}する＿＿しています。", ["ように", "ながら", "ばかり", "ほど"], "I try to exercise every day.", "Dictionary form + ようにしている = make an effort to …."],
    ["27", 2, "{来月|らいげつ}から{日本語|にほんご}の{学校|がっこう}に{通|かよ}う＿＿しました。", ["ことに", "ながら", "ほど", "ばかり"], "I decided to attend a Japanese school from next month.", "Dictionary form + ことにする = decide to …."],
    ["28", 3, "{来月|らいげつ}、{大阪|おおさか}に{引|ひ}っ{越|こ}す＿＿なりました。", ["ことに", "ながら", "ほど", "ばかり"], "It has been decided that I'll move to Osaka next month.", "〜ことになる = it has been decided / it turns out that …."],
    ["29", 2, "{今|いま}、{出|で}かける＿＿です。", ["ところ", "ながら", "ほど", "まま"], "I'm just about to go out.", "Dictionary form + ところ = about to do …."],
    ["30", 2, "{私|わたし}は{昼|ひる}ごはんを{食|た}べた＿＿です。", ["ばかり", "ながら", "ほど", "ずつ"], "I have just eaten lunch.", "た-form + ばかり = have just done …."],
    ["31", 2, "このカレーは{辛|から}＿＿て、{食|た}べられません。", ["すぎ", "すぎる", "すぎた", "すぎて"], "This curry is too spicy; I can't eat it.", "Stem + すぎる = too much. Before て: 辛すぎて."],
    ["32", 2, "このペンは{書|か}き＿＿です。", ["やすい", "やすく", "やすかっ", "やすいで"], "This pen is easy to write with.", "Stem + やすい = easy to …."],
    ["33", 3, "{字|じ}が{小|ちい}さいので、この{本|ほん}は{読|よ}み＿＿です。", ["にくい", "やすい", "すぎる", "たい"], "The print is small, so this book is hard to read.", "Stem + にくい = hard to …."],
    ["34", 2, "{明日|あした}は{雪|ゆき}が{降|ふ}る＿＿。", ["かもしれません", "かもしません", "かもしれる", "かもれません"], "It might snow tomorrow.", "〜かもしれません = might / perhaps."],
    ["35", 2, "{明日|あした}は{雨|あめ}が{降|ふ}る＿＿。", ["でしょう", "ましょう", "でしよう", "だしょう"], "It will probably rain tomorrow.", "Plain form + でしょう = probably."],
    ["36", 3, "{高|たか}く＿＿、{買|か}います。", ["ても", "たら", "ずに", "ない"], "Even if it's expensive, I'll buy it.", "い-adjective: drop い + くても = even if / even though."],
    ["37", 3, "{寝|ね}ている＿＿に、{泥棒|どろぼう}が{入|はい}りました。", ["間", "前", "後", "度"], "A thief came in while I was asleep.", "〜ている{間|あいだ}に = while … is going on."],
    ["38", 3, "{子|こ}ども＿＿わかります。", ["でも", "しか", "から", "より"], "Even a child understands.", "Noun + でも = even (a child)."],
    ["39", 2, "{日曜日|にちようび}は{本|ほん}を{読|よ}んだり、{映画|えいが}を{見|み}＿＿します。", ["たり", "て", "たら", "ながら"], "On Sundays I do things like reading and watching movies.", "〜たり〜たりする = do things such as … and …."],
    ["40", 2, "A「{重|おも}そうですね。{荷物|にもつ}を{持|も}ち＿＿か。」\nB「ありがとう。」", ["ましょう", "ました", "ません", "たい"], "A: That looks heavy. Shall I carry your luggage? B: Thank you.", "Stem + ましょうか = Shall I …? (offer)."],
    ["41", 3, "すみません、{窓|まど}を{閉|し}めて＿＿ませんか。", ["いただけ", "いただき", "くだ", "もらい"], "Excuse me, could you close the window?", "〜ていただけませんか = polite request (\"Could you please …?\")."],
    ["42", 3, "{先生|せんせい}はもう{昼|ひる}ごはんを＿＿ましたか。", ["{召|め}し{上|あ}がり", "{食|た}べさせ", "{頂|いただ}き", "{申|もう}し"], "Has the teacher already had lunch?", "{召|め}し{上|あ}がる = honorific for 食べる / 飲む (for others)."],
    ["43", 3, "{私|わたし}は{田中|たなか}＿＿。", ["と{申|もう}します", "と{召|め}し{上|あ}がります", "といらっしゃいます", "とおっしゃいます"], "My name is Tanaka.", "{申|もう}す = humble form of 言う (used about yourself)."],
    ["44", 3, "{先生|せんせい}が{学校|がっこう}に＿＿。", ["いらっしゃいます", "{参|まい}ります", "{申|もう}します", "{頂|いただ}きます"], "The teacher is at (coming to) school.", "いらっしゃる = honorific for いる / 行く / 来る (for others)."],
    ["45", 2, "{明日|あした}は{雨|あめ}が{降|ふ}る＿＿{思|おも}います。", ["と", "に", "を", "へ"], "I think it will rain tomorrow.", "Plain form + と思います = I think that …."],
    ["46", 3, "{日本語|にほんご}が{話|はな}せる＿＿なりました。", ["ように", "ことに", "ために", "ながら"], "I've become able to speak Japanese.", "Potential + ようになる = come to be able to …."],
    ["47", 3, "{先生|せんせい}に{叱|しか}ら＿＿。", ["れました", "れれました", "らりました", "られれました"], "I was scolded by the teacher.", "Passive of godan verbs: u → areru. {叱|しか}る → {叱|しか}られる."],
    ["48", 2, "{音|おと}を{小|ちい}さ＿＿してください。", ["く", "に", "な", "の"], "Please turn the sound down.", "い-adjective: drop い + く + する = make it …."],
    ["49", 1, "{私|わたし}はコーヒー＿＿します。", ["に", "を", "が", "で"], "I'll have coffee.", "Noun + にする = decide on / choose."],
    ["50", 2, "{電車|でんしゃ}より{飛行機|ひこうき}＿＿が{速|はや}いです。", ["の{方|ほう}", "の{中|なか}", "の{上|うえ}", "の{下|した}"], "Airplanes are faster than trains.", "A より B の{方|ほう}が … = B is more … than A."],
    ["51", 2, "スポーツの{中|なか}＿＿、{何|なに}が{一番|いちばん}{好|す}きですか。", ["で", "に", "を", "へ"], "Among sports, which do you like best?", "〜の中で一番 = the most among …."],
    ["52", 3, "{明日|あした}＿＿、この{宿題|しゅくだい}を{出|だ}してください。", ["までに", "まで", "から", "ので"], "Please hand in this homework by tomorrow.", "〜までに = by (a deadline). 〜まで = until (continuing)."],
    ["53", 3, "{彼|かれ}が{来|く}る＿＿わかりません。", ["かどうか", "かないか", "かなか", "かので"], "I don't know whether he will come.", "〜かどうか = whether or not."],
    ["54", 3, "ちょっと{考|かんが}え＿＿ください。", ["させて", "られて", "させる", "されて"], "Please let me think about it for a moment.", "Causative て-form + ください = please let me …."],
    ["55", 2, "{私|わたし}は{泳|およ}ぐ＿＿ができます。", ["こと", "の", "もの", "ほう"], "I can swim.", "Dictionary form + ことができる = can do …."],
    ["56", 2, "{早|はや}く{寝|ね}＿＿。", ["なさい", "ください", "だです", "ですます"], "Go to bed early.", "Stem + なさい = a command from a parent or teacher."],
    ["57", 2, "{私|わたし}は{子|こ}どもの{時|とき}、よく{川|かわ}で{泳|およ}い＿＿。", ["だ", "で", "た", "て"], "When I was a child, I often swam in the river.", "泳ぐ → 泳いだ (past, plain). Verbs ending in ぐ use だ."],
    ["58", 3, "{日本|にほん}に{来|き}て、もう{三年|さんねん}＿＿なります。", ["に", "が", "を", "で"], "It's already been three years since I came to Japan.", "Time + になる = it has been … (a length of time)."],
    ["59", 2, "{駅|えき}まで{歩|ある}いて{十分|じゅっぷん}＿＿かかります。", ["ぐらい", "ごろ", "ずつ", "ほか"], "It takes about ten minutes to walk to the station.", "Amount + ぐらい = about. ごろ is for clock times."]
  ]);

  // ---------- Vocabulary in context ----------
  add("v", [
    ["01", 1, "{私|わたし}の＿＿は{写真|しゃしん}を{撮|と}ることです。", ["{趣味|しゅみ}", "{習慣|しゅうかん}", "{約束|やくそく}", "{予約|よやく}"], "My hobby is taking photos.", "{趣味|しゅみ} = hobby."],
    ["02", 1, "{友達|ともだち}と{明日|あした}{会|あ}う＿＿をしました。", ["{約束|やくそく}", "{趣味|しゅみ}", "{準備|じゅんび}", "{心配|しんぱい}"], "I made a promise to meet my friend tomorrow.", "{約束|やくそく} = promise / appointment."],
    ["03", 1, "レストランを＿＿しました。", ["{予約|よやく}", "{散歩|さんぽ}", "{掃除|そうじ}", "{洗濯|せんたく}"], "I booked the restaurant.", "{予約|よやく}する = to reserve."],
    ["04", 2, "{旅行|りょこう}の＿＿をしています。", ["{準備|じゅんび}", "{地震|じしん}", "{季節|きせつ}", "{辞書|じしょ}"], "I'm preparing for the trip.", "{準備|じゅんび} = preparation."],
    ["05", 2, "{子|こ}どもが{病気|びょうき}で＿＿です。", ["{心配|しんぱい}", "{上手|じょうず}", "{丈夫|じょうぶ}", "{有名|ゆうめい}"], "My child is sick, so I'm worried.", "{心配|しんぱい} = worry."],
    ["06", 2, "{日本|にほん}で{働|はたら}いた＿＿があります。", ["{経験|けいけん}", "{趣味|しゅみ}", "{習慣|しゅうかん}", "{予定|よてい}"], "I have experience working in Japan.", "{経験|けいけん} = experience."],
    ["07", 1, "{来週|らいしゅう}の＿＿は{何|なん}ですか。", ["{予定|よてい}", "{経験|けいけん}", "{趣味|しゅみ}", "{事故|じこ}"], "What are your plans for next week?", "{予定|よてい} = plan / schedule."],
    ["08", 2, "{電車|でんしゃ}の＿＿で、{会社|かいしゃ}に{遅|おく}れました。", ["{事故|じこ}", "{趣味|しゅみ}", "{習慣|しゅうかん}", "{経験|けいけん}"], "Because of a train accident, I was late for work.", "{事故|じこ} = accident."],
    ["09", 1, "{日本|にほん}には{四|よっ}つの＿＿があります。", ["{季節|きせつ}", "{習慣|しゅうかん}", "{予約|よやく}", "{運動|うんどう}"], "Japan has four seasons.", "{季節|きせつ} = season."],
    ["10", 2, "{毎朝|まいあさ}{散歩|さんぽ}するのが＿＿です。", ["{習慣|しゅうかん}", "{事故|じこ}", "{地震|じしん}", "{辞書|じしょ}"], "Walking every morning is my habit.", "{習慣|しゅうかん} = habit / custom."],
    ["11", 1, "{昨日|きのう}、{大|おお}きい＿＿がありました。", ["{地震|じしん}", "{趣味|しゅみ}", "{習慣|しゅうかん}", "{経験|けいけん}"], "There was a big earthquake yesterday.", "{地震|じしん} = earthquake."],
    ["12", 1, "{毎日|まいにち}＿＿をして、{健康|けんこう}に{気|き}をつけています。", ["{運動|うんどう}", "{約束|やくそく}", "{予約|よやく}", "{事故|じこ}"], "I exercise every day and take care of my health.", "{運動|うんどう} = exercise."],
    ["13", 1, "{休|やす}みの{日|ひ}は{部屋|へや}の＿＿をします。", ["{掃除|そうじ}", "{趣味|しゅみ}", "{経験|けいけん}", "{地震|じしん}"], "On days off I clean my room.", "{掃除|そうじ} = cleaning."],
    ["14", 1, "{天気|てんき}がいいので、＿＿をします。", ["{洗濯|せんたく}", "{地震|じしん}", "{季節|きせつ}", "{辞書|じしょ}"], "The weather is nice, so I'll do the laundry.", "{洗濯|せんたく} = laundry."],
    ["15", 2, "このかばんは＿＿で、{長|なが}く{使|つか}えます。", ["{丈夫|じょうぶ}", "{心配|しんぱい}", "{上手|じょうず}", "{簡単|かんたん}"], "This bag is sturdy and can be used for a long time.", "{丈夫|じょうぶ} = strong, durable, healthy."],
    ["16", 2, "この{問題|もんだい}は＿＿ですから、すぐできます。", ["{簡単|かんたん}", "{大変|たいへん}", "{複雑|ふくざつ}", "{無理|むり}"], "This problem is easy, so I can do it right away.", "{簡単|かんたん} = simple, easy."],
    ["17", 2, "{宿題|しゅくだい}がたくさんあって、＿＿です。", ["{大変|たいへん}", "{簡単|かんたん}", "{丈夫|じょうぶ}", "{上手|じょうず}"], "I have a lot of homework, so it's tough.", "{大変|たいへん} = hard, serious, a lot of trouble."],
    ["18", 3, "{一日|いちにち}で{全部|ぜんぶ}{読|よ}むのは＿＿です。", ["{無理|むり}", "{丈夫|じょうぶ}", "{上手|じょうず}", "{地震|じしん}"], "Reading it all in one day is impossible.", "{無理|むり} = impossible, unreasonable."],
    ["19", 2, "{電車|でんしゃ}が＿＿て、{会社|かいしゃ}に{遅刻|ちこく}しました。", ["{遅|おく}れ", "{急|いそ}ぎ", "{届|とど}き", "{続|つづ}き"], "The train was delayed, so I was late for work.", "{遅|おく}れる = to be late / delayed."],
    ["20", 2, "{漢字|かんじ}を＿＿ました。", ["{間違|まちが}え", "{通|とお}り", "{届|とど}け", "{動|うご}き"], "I got the kanji wrong.", "{間違|まちが}える = to make a mistake."],
    ["21", 2, "{荷物|にもつ}が＿＿ました。", ["{届|とど}き", "{間違|まちが}え", "{集|あつ}め", "{決|き}め"], "The package arrived.", "{届|とど}く = to arrive, to reach."],
    ["22", 2, "{毎日|まいにち}{日本語|にほんご}の{勉強|べんきょう}を＿＿ています。", ["{続|つづ}け", "{届|とど}け", "{間違|まちが}え", "{集|あつ}め"], "I keep studying Japanese every day.", "{続|つづ}ける = to continue."],
    ["23", 2, "{旅行|りょこう}の{行|い}き{先|さき}を＿＿ました。", ["{決|き}め", "{続|つづ}き", "{届|とど}き", "{動|うご}き"], "I decided on the travel destination.", "{決|き}める = to decide."],
    ["24", 2, "{駅|えき}の{前|まえ}に{皆|みんな}が＿＿ました。", ["{集|あつ}まり", "{間違|まちが}え", "{届|とど}け", "{続|つづ}け"], "Everyone gathered in front of the station.", "{集|あつ}まる = to gather."],
    ["25", 2, "{部屋|へや}を＿＿ました。", ["{片付|かたづ}け", "{集|あつ}まり", "{届|とど}き", "{遅|おく}れ"], "I tidied up the room.", "{片付|かたづ}ける = to tidy up."],
    ["26", 2, "{友達|ともだち}を{誕生日|たんじょうび}パーティーに＿＿しました。", ["{招待|しょうたい}", "{運動|うんどう}", "{経験|けいけん}", "{地震|じしん}"], "I invited my friends to the birthday party.", "{招待|しょうたい} = invitation."]
  ]);
})();
