// Hand-written N3 questions. Row format: [id, difficulty, question, [correct, wrong, wrong, wrong], English, note]
// Markup: {漢字|かんじ} = furigana, ＿＿ = blank. The correct answer is listed first; the app shuffles the choices.
(function () {
  window.QUESTIONS = window.QUESTIONS || [];
  const add = (t, rows) => rows.forEach(([id, d, q, c, en, note]) => window.QUESTIONS.push({ id: "n3" + t + id, lv: 3, t, d, q, c, a: 0, en, note }));
  const W = ["ごと", "まま", "うち", "ほど"]; // clearly-wrong filler words

  add("g", [
    ["01", 3, "{十年|じゅうねん}も{日本|にほん}に{住|す}んでいたのか。{日本語|にほんご}が{上手|じょうず}な＿＿だ。", ["わけ", ...W.slice(0, 3)], "He lived in Japan for ten years. No wonder his Japanese is good.", "〜わけだ = no wonder / that explains it."],
    ["02", 3, "{彼女|かのじょ}は{怒|おこ}っている＿＿ではない。ただ{疲|つか}れているだけだ。", ["わけ", ...W.slice(0, 3)], "She isn't angry. She's just tired.", "〜わけではない = it doesn't mean that …."],
    ["03", 3, "{明日|あした}は{試験|しけん}だから、{遊|あそ}びに{行|い}く＿＿にはいかない。", ["わけ", "つもり", "はず", "ところ"], "Tomorrow is the exam, so I can't go out to play.", "〜わけにはいかない = cannot (because of circumstances)."],
    ["04", 3, "{彼|かれ}が{嘘|うそ}をつく＿＿がない。", ["はず", "ため", ...W.slice(0, 2)], "There's no way he would lie.", "〜はずがない = it's impossible that …."],
    ["05", 3, "{電気|でんき}がついているから、{彼|かれ}はまだ{会社|かいしゃ}にいる＿＿。", ["に{違|ちが}いない", "ようにする", "ことにする", "ばかりだ"], "The light is on, so he must still be at the office.", "〜に違いない = must be / no doubt."],
    ["06", 3, "{来週|らいしゅう}、{新|あたら}しい{店|みせ}ができる＿＿。（I heard it from someone.）", ["らしい", "ごと", "まま", "ずつ"], "I hear a new shop will open next week.", "〜らしい = I hear / it seems (based on information)."],
    ["07", 2, "{冬|ふゆ}は{風邪|かぜ}をひき＿＿です。", ["がち", "っぽい", "ごと", "ずつ"], "In winter I tend to catch colds.", "Stem + がち = tends to …."],
    ["08", 2, "{風邪|かぜ}＿＿なので、{早|はや}く{寝|ね}ます。", ["{気味|ぎみ}", "っぽい", "ごと", "ずつ"], "I have a bit of a cold, so I'll go to bed early.", "Noun / stem + 気味 = a touch of …."],
    ["09", 2, "{買|か}い{物|もの}の＿＿に、{郵便局|ゆうびんきょく}にも{寄|よ}りました。", ["ついで", "うち", "まま", "ほど"], "While shopping I also dropped by the post office.", "〜のついでに = while I'm at it."],
    ["10", 3, "{家|いえ}を{出|で}た＿＿、{雨|あめ}が{降|ふ}り{出|だ}した。", ["とたん", "ばかり", "まま", "ほど"], "The moment I left the house, it started to rain.", "た-form + とたん = the instant that …."],
    ["11", 3, "{病気|びょうき}になっ＿＿、{健康|けんこう}のありがたさが{分|わ}かった。", ["てはじめて", "たとたん", "たまま", "たばかり"], "Only after getting sick did I appreciate good health.", "て-form + はじめて = only after …."],
    ["12", 3, "{結果|けっか}が{分|わ}かり＿＿、{連絡|れんらく}します。", ["{次第|しだい}", "とたん", "ばかり", "ごと"], "I'll contact you as soon as I know the result.", "Stem + 次第 = as soon as …."],
    ["13", 3, "この{状況|じょうきょう}では、{反対|はんたい}せ＿＿を{得|え}ない。", ["ざる", "ず", "ない", "ぬ"], "In this situation I have no choice but to object.", "ない-form (without ない) + ざるを得ない = have no choice but to …. する → せざる."],
    ["14", 3, "{年|とし}を{取|と}る＿＿、{体力|たいりょく}が{落|お}ちる。", ["につれて", "ついでに", "とたん", "ばかりに"], "As one gets older, physical strength declines.", "〜につれて = as … (gradual change)."],
    ["15", 3, "{先生|せんせい}の＿＿で、{合格|ごうかく}できました。", ["おかげ", "せい", "くせ", "ため"], "Thanks to my teacher, I passed.", "〜おかげで = thanks to (good result). 〜せいで is for blame."],
    ["16", 3, "{寝坊|ねぼう}した＿＿、{会議|かいぎ}に{遅|おく}れた。", ["せいで", "ついでに", "ながら", "まま"], "Because I overslept, I was late for the meeting.", "〜せいで = because of … (bad result)."],
    ["17", 3, "{知|し}っている＿＿、{教|おし}えてくれなかった。", ["くせに", "おかげで", "ついでに", "たびに"], "Even though he knew, he didn't tell me.", "〜くせに = even though … (criticism)."],
    ["18", 3, "{春|はる}＿＿、まだ{寒|さむ}い。", ["とはいえ", "のおかげで", "のたびに", "のついでに"], "Though it's spring, it's still cold.", "〜とはいえ = even though / that said."],
    ["19", 3, "{買|か}ってみた＿＿、{使|つか}わなかった。", ["ものの", "おかげで", "たびに", "ついでに"], "I bought it, but I didn't use it.", "〜ものの = although …, but …."],
    ["20", 3, "{彼|かれ}は{医者|いしゃ}であると＿＿、{作家|さっか}でもある。", ["{同時|どうじ}に", "ついでに", "おかげで", "ばかりに"], "He is a doctor and, at the same time, a writer.", "〜と同時に = at the same time as …."],
    ["21", 3, "{去年|きょねん}＿＿、{今年|ことし}は{暑|あつ}い。", ["に{比|くら}べて", "について", "によって", "として"], "Compared with last year, this year is hot.", "〜に比べて = compared with …."],
    ["22", 3, "{兄|あに}は{静|しず}かなの＿＿、{弟|おとうと}は{元気|げんき}だ。", ["に{対|たい}して", "について", "によって", "として"], "In contrast to my quiet older brother, my younger brother is lively.", "〜のに対して = in contrast to …."],
    ["23", 3, "{練習|れんしゅう}すれば＿＿ほど、{上手|じょうず}になる。", ["する", "した", "して", "しない"], "The more you practise, the better you get.", "Verb ば-form + dictionary form + ほど = the more … the more …."],
    ["24", 2, "{説明書|せつめいしょ}の＿＿に{組|く}み{立|た}ててください。", ["とおり", "まま", "うち", "ごと"], "Please assemble it as the instructions say.", "Noun + のとおりに = exactly as …."],
    ["25", 2, "{電気|でんき}をつけた＿＿、{寝|ね}てしまった。", ["まま", "とおり", "うち", "ごと"], "I fell asleep with the light on.", "た-form + まま = left in that state."],
    ["26", 2, "ドアを{開|あ}け＿＿にしないでください。", ["っぱなし", "がち", "っぽい", "{気味|ぎみ}"], "Please don't leave the door open.", "Stem + っぱなし = left (carelessly) in that state."],
    ["27", 3, "{日本|にほん}では、{家|いえ}に{入|はい}る{前|まえ}に{靴|くつ}を{脱|ぬ}ぐ＿＿なっている。", ["ことに", "ながら", "ばかり", "ほど"], "In Japan, it's the custom to take off your shoes before entering a house.", "〜ことになっている = it is the rule / custom that …."],
    ["28", 3, "{学生|がくせい}は{勉強|べんきょう}する＿＿だ。", ["べき", "まま", "ごと", "ほど"], "Students should study.", "Dictionary form + べきだ = should."],
    ["29", 3, "{子|こ}どもの{頃|ころ}は、よく{川|かわ}で{遊|あそ}んだ＿＿だ。", ["もの", "ごと", "まま", "うち"], "As a child, I used to play in the river a lot.", "〜たものだ = used to … (nostalgia)."],
    ["30", 3, "{健康|けんこう}のためには、{毎日|まいにち}{運動|うんどう}する＿＿だ。", ["こと", "まま", "ごと", "うち"], "For your health, you should exercise every day.", "Dictionary form + ことだ = you should … (advice)."],
    ["31", 3, "{英語|えいご}＿＿、{中国語|ちゅうごくご}も{話|はな}せる。", ["はもちろん", "のせいで", "のうちに", "ばかりに"], "He speaks Chinese, not to mention English.", "〜はもちろん = not to mention …."],
    ["32", 3, "{彼|かれ}は{頭|あたま}がいい＿＿でなく、{性格|せいかく}もいい。", ["ばかり", "ごと", "まま", "うち"], "He's not only smart, but has a good personality too.", "〜ばかりでなく = not only … but also …."],
    ["33", 3, "{忙|いそが}しくて、{食事|しょくじ}をする{時間|じかん}＿＿ない。", ["さえ", "まま", "ごと", "うち"], "I'm so busy I don't even have time to eat.", "〜さえ = even …."],
    ["34", 3, "{今年|ことし}＿＿、{合格|ごうかく}したい。", ["こそ", "ごと", "まま", "うち"], "This year, for sure, I want to pass.", "〜こそ = precisely / this time for sure."],
    ["35", 3, "{初|はじ}めて＿＿、{上手|じょうず}に{作|つく}れた。", ["にしては", "について", "として", "によって"], "For a first try, I made it well.", "〜にしては = considering that …."],
    ["36", 2, "{天気予報|てんきよほう}＿＿、{明日|あした}は{雨|あめ}だ。", ["によると", "について", "として", "にとって"], "According to the weather forecast, it will rain tomorrow.", "〜によると = according to …."],
    ["37", 3, "{駅|えき}を＿＿に、{店|みせ}が{並|なら}んでいる。", ["{中心|ちゅうしん}", "{最中|さいちゅう}", "{以上|いじょう}", "{同時|どうじ}"], "Shops line up around the station.", "〜を中心に = centering on …."],
    ["38", 3, "{社長|しゃちょう}を＿＿、{社員|しゃいん}{全員|ぜんいん}が{参加|さんか}した。", ["はじめ", "かけ", "だらけ", "ついで"], "All the employees, starting with the president, took part.", "〜をはじめ = starting with …."],
    ["39", 3, "{一年|いちねん}＿＿、{暖|あたた}かい{地域|ちいき}だ。", ["を{通|とお}して", "について", "に{対|たい}して", "にとって"], "It's a warm region throughout the year.", "〜を通して = throughout / through."],
    ["40", 3, "{読|よ}み＿＿の{本|ほん}が{机|つくえ}の{上|うえ}にある。", ["かけ", "ごと", "まま", "ずつ"], "A half-read book is on the desk.", "Stem + かけ = half-done / in the middle of …."],
    ["41", 3, "このケーキは{大|おお}きくて、{食|た}べ＿＿ません。", ["きれ", "ごと", "まま", "ずつ"], "This cake is so big I can't finish eating it.", "Stem + きれない = can't finish …."],
    ["42", 3, "{突然|とつぜん}、{雨|あめ}が{降|ふ}り＿＿。", ["{出|だ}した", "きった", "すぎた", "やすい"], "Suddenly it started to rain.", "Stem + 出す = suddenly start to …."],
    ["43", 3, "{薬|くすり}を{飲|の}ま＿＿{済|す}んだ。", ["ずに", "ないと", "ずで", "ないに"], "I got by without taking medicine.", "〜ずに済む = manage without doing …."],
    ["44", 3, "{眠|ねむ}くて＿＿。", ["たまらない", "かまわない", "わからない", "しかたい"], "I'm unbearably sleepy.", "〜てたまらない = unbearably …."],
    ["45", 3, "{連絡先|れんらくさき}が{分|わ}からないので、{連絡|れんらく}し＿＿がない。", ["ようが", "ことが", "ものが", "はずが"], "I don't know his contact details, so there's no way to reach him.", "Stem + ようがない = there's no way to …."],
    ["46", 3, "それは{十分|じゅうぶん}あり＿＿ことだ。", ["{得|う}る", "かねる", "がたい", "かけた"], "That is entirely possible.", "Stem + 得る (うる) = it is possible that …."],
    ["47", 3, "{日本|にほん}＿＿、{桜|さくら}を{思|おも}い{出|だ}す。", ["というと", "だけでは", "ところで", "ついでに"], "Speaking of Japan, I think of cherry blossoms.", "〜というと = speaking of …."],
    ["48", 3, "{行|い}ってみた。＿＿、{店|みせ}は{閉|し}まっていた。", ["ところが", "だから", "それで", "ですから"], "I went. But the shop was closed.", "ところが = but / however (unexpected result)."],
    ["49", 3, "＿＿、{明日|あした}の{予定|よてい}は？", ["ところで", "ところが", "だから", "しかし"], "By the way, what are tomorrow's plans?", "ところで = by the way (changing the topic)."],
    ["50", 3, "{入学|にゅうがく}に＿＿、{書類|しょるい}を{提出|ていしゅつ}してください。", ["{際|さい}して", "{関|かん}して", "{対|たい}して", "{比|くら}べて"], "Please submit the documents upon admission.", "〜に際して = on the occasion of …."],
    ["51", 3, "{約束|やくそく}した＿＿、{守|まも}らなければならない。", ["{以上|いじょう}", "ついで", "おかげ", "せい"], "Now that I've promised, I must keep my word.", "〜以上 = now that / since …."],
    ["52", 3, "やる＿＿には、{最後|さいご}までやる。", ["から", "ほど", "おかげ", "せい"], "Since I'm going to do it, I'll see it through.", "〜からには = now that … (strong resolve)."],
    ["53", 3, "{髪|かみ}が{長|なが}い＿＿から、{女性|じょせい}だと{思|おも}った。", ["こと", "もの", "の", "ところ"], "From the fact that the hair was long, I thought it was a woman.", "〜ことから = from the fact that …."],
    ["54", 3, "{六月|ろくがつ}＿＿{七月|しちがつ}にかけて、{雨|あめ}が{多|おお}い。", ["から", "まで", "より", "ほど"], "From June through July there's a lot of rain.", "AからBにかけて = from A through B."],
    ["55", 3, "{彼|かれ}に{会|あ}う＿＿、{元気|げんき}をもらう。", ["たびに", "ついでに", "とたん", "おかげで"], "Every time I meet him, I get energy.", "〜たびに = every time …."],
    ["56", 3, "{若|わか}い＿＿に、いろいろな{経験|けいけん}をしたほうがいい。", ["うち", "まま", "ごと", "ほど"], "While you're young, you should have many experiences.", "〜うちに = while it's still the case."],
    ["57", 3, "{食事|しょくじ}の＿＿に、{電話|でんわ}が{鳴|な}った。", ["{最中|さいちゅう}", "{以上|いじょう}", "{同時|どうじ}", "{通|とお}り"], "The phone rang right in the middle of the meal.", "〜の最中に = right in the middle of …."],
    ["58", 3, "{嘘|うそ}をついた＿＿に、{信用|しんよう}を{失|うしな}った。", ["ばかり", "たび", "とたん", "ついで"], "Just because I lied, I lost people's trust.", "〜たばかりに = just because … (bad result)."],
    ["59", 3, "{高|たか}いから＿＿って、いい{物|もの}とは{限|かぎ}らない。", ["と", "に", "を", "が"], "Just because it's expensive doesn't mean it's good.", "〜からといって = just because …."],
    ["60", 3, "{高|たか}い{物|もの}がいい{物|もの}とは＿＿。", ["{限|かぎ}らない", "{分|わ}からない", "{足|た}らない", "{通|とお}らない"], "Expensive things are not necessarily good.", "〜とは限らない = not necessarily."],
    ["61", 3, "{彼|かれ}は{何|なに}も{知|し}らない＿＿ように{話|はな}した。", ["かの", "ものの", "くせに", "せいで"], "He spoke as if he knew nothing.", "〜かのように = as if …."],
    ["62", 3, "{値段|ねだん}＿＿、{味|あじ}がいい。", ["のわりに", "のおかげに", "のたびに", "のついでに"], "The taste is good for the price.", "〜のわりに = considering …."],
    ["63", 2, "{部屋|へや}がごみ＿＿だ。", ["だらけ", "ごと", "まま", "ほど"], "The room is full of trash.", "Noun + だらけ = full of / covered with (usually bad)."],
    ["64", 3, "{信|しん}じ＿＿{話|はなし}だ。", ["がたい", "すぎる", "ごと", "まま"], "It's a hard-to-believe story.", "Stem + がたい = hard to … (feelings, judgement)."],
    ["65", 3, "{景気|けいき}は{回復|かいふく}し＿＿ある。", ["つつ", "ながら", "ついで", "ばかり"], "The economy is recovering.", "Stem + つつある = is in the process of …."],
    ["66", 3, "{台風|たいふう}が{上陸|じょうりく}する＿＿がある。", ["おそれ", "つもり", "はず", "ため"], "There is a risk that the typhoon will make landfall.", "〜おそれがある = there is a risk that …."],
    ["67", 3, "そんなに{心配|しんぱい}する＿＿はない。", ["こと", "まま", "ごと", "ほど"], "There's no need to worry that much.", "〜ことはない = there is no need to …."],
    ["68", 3, "その{質問|しつもん}にはお{答|こた}えし＿＿ます。", ["かね", "やすい", "すぎ", "がち"], "I'm afraid I can't answer that question.", "Stem + かねる = unable to … (polite refusal)."],
    ["69", 3, "このままでは、{事故|じこ}になり＿＿。", ["かねない", "がたい", "かけない", "ごとない"], "At this rate, it could lead to an accident.", "Stem + かねない = might … (a bad outcome)."],
    ["70", 3, "{上手|じょうず}＿＿、{全然|ぜんぜん}できない。", ["どころか", "のおかげで", "のついでに", "のたびに"], "Far from being good, I can't do it at all.", "〜どころか = far from …."],
    ["71", 3, "{彼|かれ}が{勝|か}つ＿＿{決|き}まっている。", ["に", "を", "が", "で"], "He is sure to win.", "〜に決まっている = surely / it's certain that …."],
    ["72", 3, "{日本|にほん}の{歴史|れきし}＿＿、{本|ほん}を{読|よ}んだ。", ["に{関|かん}して", "に{比|くら}べて", "に{際|さい}して", "に{従|したが}って"], "I read a book regarding Japanese history.", "〜に関して = regarding …."],
    ["73", 3, "{年齢|ねんれい}＿＿、{誰|だれ}でも{参加|さんか}できる。", ["を{問|と}わず", "に{比|くら}べず", "について", "に{際|さい}して"], "Anyone can take part regardless of age.", "〜を問わず = regardless of …."],
    ["74", 3, "{日本|にほん}＿＿、{世界中|せかいじゅう}で{人気|にんき}がある。", ["に{限|かぎ}らず", "について", "に{際|さい}して", "に{比|くら}べて"], "It's popular not only in Japan but all over the world.", "〜に限らず = not limited to …."],
    ["75", 3, "{社長|しゃちょう}は{来週|らいしゅう}、{帰国|きこく}する＿＿ことだ。", ["という", "だけの", "ばかりの", "ごとの"], "I hear the president will return home next week.", "〜ということだ = I hear that …."]
  ]);

  add("v", [
    ["01", 2, "{明日|あした}の＿＿に{遅|おく}れないように、{早|はや}く{寝|ね}ます。", ["{会議|かいぎ}", "{原因|げんいん}", "{影響|えいきょう}", "{態度|たいど}"], "I'll go to bed early so I'm not late for tomorrow's meeting.", "{会議|かいぎ} = meeting."],
    ["02", 2, "{先生|せんせい}に{進路|しんろ}について＿＿しました。", ["{相談|そうだん}", "{出席|しゅっせき}", "{提出|ていしゅつ}", "{遅刻|ちこく}"], "I consulted my teacher about my future path.", "{相談|そうだん}する = to consult / talk over."],
    ["03", 2, "{宿題|しゅくだい}は{明日|あした}までに＿＿してください。", ["{提出|ていしゅつ}", "{相談|そうだん}", "{出席|しゅっせき}", "{欠席|けっせき}"], "Please hand in your homework by tomorrow.", "{提出|ていしゅつ}する = to submit."],
    ["04", 2, "{事故|じこ}の＿＿は、まだ{分|わ}かっていません。", ["{原因|げんいん}", "{態度|たいど}", "{印象|いんしょう}", "{習慣|しゅうかん}"], "The cause of the accident is still unknown.", "{原因|げんいん} = cause."],
    ["05", 1, "{試験|しけん}の＿＿が{出|で}ました。{合格|ごうかく}です！", ["{結果|けっか}", "{原因|げんいん}", "{印象|いんしょう}", "{準備|じゅんび}"], "The exam results are out. I passed!", "{結果|けっか} = result."],
    ["06", 2, "{彼|かれ}の＿＿は{悪|わる}かった。{私|わたし}は{彼|かれ}が{嫌|きら}いになった。", ["{態度|たいど}", "{結果|けっか}", "{資料|しりょう}", "{地震|じしん}"], "His attitude was bad. I came to dislike him.", "{態度|たいど} = attitude."],
    ["07", 2, "{会議|かいぎ}の＿＿を{印刷|いんさつ}してください。", ["{資料|しりょう}", "{印象|いんしょう}", "{態度|たいど}", "{習慣|しゅうかん}"], "Please print the materials for the meeting.", "{資料|しりょう} = materials / documents."],
    ["08", 3, "この{仕事|しごと}は{大|おお}きな＿＿があります。{失敗|しっぱい}は{許|ゆる}されません。", ["{責任|せきにん}", "{準備|じゅんび}", "{印象|いんしょう}", "{趣味|しゅみ}"], "This job carries great responsibility. Failure is not allowed.", "{責任|せきにん} = responsibility."],
    ["09", 2, "{彼|かれ}は{毎日|まいにち}＿＿して、{日本語|にほんご}が{上手|じょうず}になった。", ["{努力|どりょく}", "{遅刻|ちこく}", "{欠席|けっせき}", "{心配|しんぱい}"], "He made an effort every day and his Japanese improved.", "{努力|どりょく} = effort."],
    ["10", 2, "インターネットで{旅行|りょこう}の＿＿を{集|あつ}めた。", ["{情報|じょうほう}", "{態度|たいど}", "{習慣|しゅうかん}", "{地震|じしん}"], "I gathered travel information on the internet.", "{情報|じょうほう} = information."],
    ["11", 3, "{新|あたら}しい＿＿を{使|つか}って、{工場|こうじょう}の{作業|さぎょう}が{楽|らく}になった。", ["{技術|ぎじゅつ}", "{印象|いんしょう}", "{態度|たいど}", "{習慣|しゅうかん}"], "Using new technology made the work at the factory easier.", "{技術|ぎじゅつ} = technology / skill."],
    ["12", 2, "＿＿を{守|まも}るために、ごみを{減|へ}らしましょう。", ["{環境|かんきょう}", "{印象|いんしょう}", "{資料|しりょう}", "{態度|たいど}"], "Let's reduce trash to protect the environment.", "{環境|かんきょう} = environment."],
    ["13", 3, "{初|はじ}めて{会|あ}った{時|とき}の＿＿は、{優|やさ}しそうな{人|ひと}だった。", ["{印象|いんしょう}", "{努力|どりょく}", "{責任|せきにん}", "{影響|えいきょう}"], "My first impression was that he looked like a kind person.", "{印象|いんしょう} = impression."],
    ["14", 3, "{来週|らいしゅう}、{会社|かいしゃ}の＿＿で、{温泉|おんせん}に{行|い}きます。", ["{旅行|りょこう}", "{態度|たいど}", "{原因|げんいん}", "{責任|せきにん}"], "Next week we're going to a hot spring on a company trip.", "{旅行|りょこう} = trip."],
    ["15", 2, "{相手|あいて}の＿＿をよく{聞|き}いてから、{話|はな}しましょう。", ["{意見|いけん}", "{印象|いんしょう}", "{結果|けっか}", "{習慣|しゅうかん}"], "Let's listen carefully to the other person's opinion before we speak.", "{意見|いけん} = opinion."]
  ]);
})();
