// More hand-written N5 questions. Row format: [id, difficulty, question, [correct, wrong, wrong, wrong], English, note]
// Markup: {漢字|かんじ} = furigana, ＿＿ = blank. The correct answer is listed first; the app shuffles the choices.
(function () {
  const add = (t, rows) => rows.forEach(([id, d, q, c, en, note]) => window.QUESTIONS.push({ id: "n5" + t + "x" + id, lv: 5, t, d, q, c, a: 0, en, note }));

  // ---------- Grammar ----------
  add("g", [
    ["11", 1, "わたしは{犬|いぬ}＿＿{好|す}きです。", ["が", "を", "に", "で"], "I like dogs.", "{好|す}きです / わかります take が for the thing you like or understand."],
    ["12", 1, "{私|わたし}は{日本語|にほんご}＿＿わかります。", ["が", "を", "に", "で"], "I understand Japanese.", "わかります takes が: 〜がわかります."],
    ["13", 1, "{机|つくえ}の{上|うえ}＿＿{本|ほん}があります。", ["に", "を", "で", "と"], "There is a book on the desk.", "Place + に + あります / います = something exists there."],
    ["14", 1, "{図書館|としょかん}＿＿{勉強|べんきょう}します。", ["で", "に", "を", "が"], "I study at the library.", "Place of an action + で."],
    ["15", 1, "はし＿＿{食|た}べます。", ["で", "を", "に", "が"], "I eat with chopsticks.", "で also marks the tool or means: はしで食べる."],
    ["16", 1, "{私|わたし}は{姉|あね}＿＿{一緒|いっしょ}に{行|い}きました。", ["と", "を", "で", "へ"], "I went together with my older sister.", "〜と = together with (a person)."],
    ["17", 2, "{朝|あさ}から{夜|よる}＿＿{働|はたら}きます。", ["まで", "より", "を", "に"], "I work from morning until night.", "〜から〜まで = from … until …."],
    ["18", 2, "{冷蔵庫|れいぞうこ}に{何|なに}＿＿ありません。", ["も", "を", "に", "で"], "There is nothing in the fridge.", "Question word + も + negative = nothing / nobody / nowhere."],
    ["19", 1, "これは{先生|せんせい}＿＿{本|ほん}です。", ["の", "を", "に", "で"], "This is the teacher's book.", "の links two nouns (possession)."],
    ["20", 1, "{来年|らいねん}、{日本|にほん}＿＿{行|い}きます。", ["へ", "を", "が", "で"], "Next year I'll go to Japan.", "へ marks direction (read \"e\")."],
    ["21", 1, "{田中|たなか}さんは{先生|せんせい}です＿＿。", ["か", "を", "に", "で"], "Is Mr. Tanaka a teacher?", "Add か at the end to make a question."],
    ["22", 2, "{財布|さいふ}に{百円|ひゃくえん}＿＿ありません。", ["しか", "を", "に", "で"], "I only have 100 yen in my wallet.", "〜しか + negative = only."],
    ["23", 2, "{夏|なつ}は{冬|ふゆ}＿＿{暑|あつ}いです。", ["より", "ほど", "まで", "から"], "Summer is hotter than winter.", "A は B より … = A is more … than B."],
    ["24", 3, "{今日|きょう}は{昨日|きのう}＿＿{寒|さむ}くないです。", ["ほど", "を", "に", "と"], "Today isn't as cold as yesterday.", "A は B ほど + negative = A is not as … as B."],
    ["25", 3, "{果物|くだもの}の{中|なか}で、りんごが＿＿{好|す}きです。", ["いちばん", "あまり", "ぜんぜん", "ちょうど"], "Of all fruits, I like apples best.", "{一番|いちばん} = the most / number one."],
    ["26", 1, "{昨日|きのう}、{映画|えいが}を{見|み}＿＿。", ["ました", "ます", "ません", "ましょう"], "I watched a movie yesterday.", "Past polite: stem + ました."],
    ["27", 2, "{私|わたし}は{肉|にく}を{食|た}べ＿＿。{野菜|やさい}だけ{食|た}べます。", ["ません", "ます", "ました", "ましょう"], "I don't eat meat. I only eat vegetables.", "Negative polite: stem + ません."],
    ["28", 2, "{朝|あさ}ごはんを{食|た}べ＿＿、{学校|がっこう}へ{行|い}きます。", ["て", "た", "ない", "ます"], "I eat breakfast and then go to school.", "て-form joins actions in sequence."],
    ["29", 2, "{手紙|てがみ}を{書|か}い＿＿、{送|おく}ります。", ["て", "た", "で", "ない"], "I write a letter and then send it.", "書く → 書いて (く becomes いて)."],
    ["30", 2, "{今|いま}、{本|ほん}を{読|よ}ん＿＿います。", ["で", "て", "た", "に"], "I'm reading a book now.", "読む → 読んで (む becomes んで). 〜ています = ongoing action."],
    ["31", 2, "{私|わたし}は{東京|とうきょう}に{住|す}ん＿＿います。", ["で", "て", "だ", "に"], "I live in Tokyo.", "住んでいます = state that continues (live, married, know…)."],
    ["32", 2, "ここで{走|はし}ら＿＿ください。", ["ないで", "なくて", "ません", "ないと"], "Please don't run here.", "ない-form + でください = please don't …."],
    ["33", 1, "{私|わたし}は{日本|にほん}へ{行|い}き＿＿です。", ["たい", "ます", "ない", "たく"], "I want to go to Japan.", "Verb stem + たい = want to …."],
    ["34", 2, "{今日|きょう}は{何|なに}も{食|た}べ＿＿です。", ["たくない", "たい", "たかった", "たくて"], "I don't want to eat anything today.", "Stem + たくない = don't want to …."],
    ["35", 2, "いっしょに{映画|えいが}を{見|み}＿＿か。", ["ません", "ませ", "まして", "ませる"], "Won't you watch a movie with me?", "Stem + ませんか = invitation (\"Won't you …?\")."],
    ["36", 2, "{昨日|きのう}は{寒|さむ}＿＿です。", ["かった", "くなかっ", "ない", "くて"], "It was cold yesterday.", "い-adjective past: drop い + かった."],
    ["37", 2, "このカレーは{辛|から}＿＿です。", ["くない", "じゃない", "ではない", "くて"], "This curry isn't spicy.", "い-adjective negative: drop い + くない."],
    ["38", 1, "ここは＿＿{町|まち}です。", ["きれいな", "きれいの", "きれいで", "きれいに"], "This is a clean town.", "な-adjective + な + noun."],
    ["39", 2, "{私|わたし}は{料理|りょうり}が{上手|じょうず}＿＿ありません。", ["では", "には", "とは", "へは"], "I'm not good at cooking.", "な-adjective negative: 〜ではありません / 〜じゃありません."],
    ["40", 2, "{冬|ふゆ}になると、{寒|さむ}＿＿なります。", ["く", "い", "な", "に"], "When winter comes, it gets cold.", "い-adjective: drop い + く + なります = becomes …."],
    ["41", 2, "{静|しず}か＿＿{歩|ある}いてください。", ["に", "く", "な", "と"], "Please walk quietly.", "な-adjective + に makes an adverb."],
    ["42", 1, "{公園|こうえん}に{子|こ}どもが＿＿。", ["います", "あります", "です", "しました"], "There are children in the park.", "います is for living things, あります for objects."],
    ["43", 1, "{机|つくえ}の{上|うえ}に{本|ほん}が＿＿。", ["あります", "います", "です", "しました"], "There is a book on the desk.", "あります is for non-living things."],
    ["44", 2, "りんごを三＿＿{買|か}いました。", ["つ", "人", "本", "枚"], "I bought three apples.", "General counter: ひとつ、ふたつ、みっつ… (三つ)."],
    ["45", 2, "{友達|ともだち}が二＿＿います。", ["人", "つ", "本", "枚"], "I have two friends.", "People: 一人 (ひとり), 二人 (ふたり), then 〜人 (さんにん)."],
    ["46", 2, "ペンを三＿＿{買|か}いました。", ["本", "人", "枚", "台"], "I bought three pens.", "Long thin objects (pens, bottles): 〜本."],
    ["47", 2, "{紙|かみ}を五＿＿ください。", ["枚", "本", "台", "人"], "Five sheets of paper, please.", "Flat things (paper, tickets, plates): 〜枚."],
    ["48", 2, "{車|くるま}が二＿＿あります。", ["台", "枚", "本", "人"], "There are two cars.", "Machines and vehicles: 〜台."],
    ["49", 1, "A「これは＿＿ですか。」\nB「それは{傘|かさ}です。」", ["何", "誰", "どこ", "いつ"], "A: What is this? B: That's an umbrella.", "{何|なん} = what."],
    ["50", 1, "A「あの{人|ひと}は＿＿ですか。」\nB「{田中|たなか}さんです。」", ["だれ", "なに", "どこ", "いつ"], "A: Who is that person? B: It's Mr. Tanaka.", "だれ = who."],
    ["51", 1, "A「{駅|えき}は＿＿ですか。」\nB「あそこです。」", ["どこ", "だれ", "なに", "いくら"], "A: Where is the station? B: Over there.", "どこ = where."],
    ["52", 1, "A「＿＿{日本|にほん}へ{行|い}きますか。」\nB「{来月|らいげつ}{行|い}きます。」", ["いつ", "どこ", "だれ", "なに"], "A: When are you going to Japan? B: Next month.", "いつ = when."],
    ["53", 1, "A「これは＿＿ですか。」\nB「{千円|せんえん}です。」", ["いくら", "いつ", "どこ", "だれ"], "A: How much is this? B: It's 1,000 yen.", "いくら = how much."],
    ["54", 2, "A「＿＿{遅|おそ}れましたか。」\nB「{電車|でんしゃ}が{止|と}まりましたから。」", ["どうして", "いつ", "だれ", "どこ"], "A: Why were you late? B: Because the train stopped.", "どうして / なぜ = why."],
    ["55", 2, "A「{田中|たなか}さんのかばんは＿＿ですか。」\nB「あの{赤|あか}いのです。」", ["どれ", "どこ", "だれ", "いつ"], "A: Which one is Mr. Tanaka's bag? B: That red one.", "どれ = which (of three or more)."],
    ["56", 2, "A「{昼|ひる}ごはんを{食|た}べましたか。」\nB「いいえ、＿＿{食|た}べていません。」", ["まだ", "もう", "とても", "いつも"], "A: Did you eat lunch? B: No, I haven't eaten yet.", "まだ + 〜ていません = not yet."],
    ["57", 2, "A「{宿題|しゅくだい}をしましたか。」\nB「はい、＿＿{終|お}わりました。」", ["もう", "まだ", "あまり", "ぜんぜん"], "A: Did you do your homework? B: Yes, I've already finished.", "もう + past = already."],
    ["58", 3, "{私|わたし}は{肉|にく}を＿＿{食|た}べません。", ["あまり", "とても", "ぜひ", "どうぞ"], "I don't eat meat very often.", "あまり + negative = not very / not often."],
    ["59", 2, "{寝|ね}る＿＿に、{歯|は}を{磨|みが}きます。", ["前", "後", "中", "間"], "I brush my teeth before going to bed.", "Dictionary form + {前|まえ}に = before …."],
    ["60", 2, "{食|た}べた＿＿で、{歯|は}を{磨|みが}きます。", ["後", "前", "中", "間"], "I brush my teeth after eating.", "た-form + {後|あと}で = after …."],
    ["61", 2, "ここで{写真|しゃしん}を{撮|と}っ＿＿もいいですか。", ["ても", "ては", "たら", "ば"], "May I take a photo here?", "て-form + もいいですか = May I …?"],
    ["62", 1, "{昨日|きのう}は{休|やす}み＿＿。", ["でした", "です", "だ", "ます"], "Yesterday was a day off.", "Past of です is でした."],
    ["63", 1, "{会議|かいぎ}は{三時|さんじ}＿＿{始|はじ}まります。", ["に", "を", "へ", "が"], "The meeting starts at three o'clock.", "A specific time + に."],
    ["64", 2, "{私|わたし}は{新|あたら}しい{車|くるま}＿＿ほしいです。", ["が", "へ", "で", "と"], "I want a new car.", "ほしい (to want a thing) takes が."],
    ["65", 2, "{図書館|としょかん}へ{本|ほん}を{借|か}り＿＿{行|い}きます。", ["に", "を", "が", "と"], "I'm going to the library to borrow a book.", "Stem + に{行|い}く = go in order to …."],
    ["66", 2, "{兄|あに}は{結婚|けっこん}し＿＿います。", ["て", "た", "ない", "ます"], "My older brother is married.", "〜ています also expresses a continuing state."]
  ]);

  // ---------- Vocabulary in context ----------
  add("v", [
    ["15", 1, "とても{疲|つか}れましたから、{早|はや}く＿＿。", ["{寝|ね}ます", "{泳|およ}ぎます", "{売|う}ります", "{習|なら}います"], "I'm very tired, so I'll go to bed early.", "{寝|ね}る = to sleep / go to bed. {疲|つか}れる = to get tired."],
    ["16", 1, "のどが{渇|かわ}きました。＿＿を{飲|の}みたいです。", ["{水|みず}", "{肉|にく}", "{靴|くつ}", "{本|ほん}"], "I'm thirsty. I want to drink water.", "{水|みず} = water."],
    ["17", 1, "{私|わたし}の{家|いえ}には{犬|いぬ}と＿＿がいます。", ["ねこ", "{車|くるま}", "{窓|まど}", "{電話|でんわ}"], "At my house there are a dog and a cat.", "ねこ = cat. いる is for living things."],
    ["18", 1, "{手紙|てがみ}を{出|だ}すとき、＿＿を{貼|は}ります。", ["{切手|きって}", "{財布|さいふ}", "{地図|ちず}", "{傘|かさ}"], "When mailing a letter, I put on a stamp.", "{切手|きって} = postage stamp."],
    ["19", 1, "この{道|みち}を＿＿{行|い}くと、{駅|えき}があります。", ["まっすぐ", "だんだん", "ちょうど", "ぜひ"], "If you go straight along this road, there's a station.", "まっすぐ = straight ahead."],
    ["20", 1, "{駅|えき}は＿＿ですから、{歩|ある}いて{行|い}けます。", ["{近|ちか}い", "{長|なが}い", "{重|おも}い", "{広|ひろ}い"], "The station is close, so I can walk.", "{近|ちか}い = near."],
    ["21", 1, "このかばんは＿＿ですから、{買|か}いません。", ["{高|たか}い", "{弱|よわ}い", "{暗|くら}い", "{遠|とお}い"], "This bag is expensive, so I won't buy it.", "{高|たか}い = expensive / tall. {高|たか}いですから = because it's expensive."],
    ["22", 1, "{私|わたし}は＿＿が{好|す}きです。{毎日|まいにち}{聞|き}いています。", ["{音楽|おんがく}", "{信号|しんごう}", "{天気|てんき}", "{住所|じゅうしょ}"], "I like music. I listen to it every day.", "{音楽|おんがく} = music."],
    ["23", 2, "{漢字|かんじ}が＿＿ですから、{何度|なんど}も{書|か}きます。", ["{難|むずか}しい", "{優|やさ}しい", "{暗|くら}い", "{忙|いそが}しい"], "Kanji are difficult, so I write them many times.", "{難|むずか}しい = difficult. Opposite: {易|やさ}しい."],
    ["24", 2, "{試験|しけん}の＿＿に、たくさん{勉強|べんきょう}しました。", ["{前|まえ}", "{右|みぎ}", "{隣|となり}", "{横|よこ}"], "I studied a lot before the exam.", "〜の{前|まえ}に = before …."],
    ["25", 2, "あの{赤|あか}い{屋根|やね}の＿＿は{図書館|としょかん}です。", ["{建物|たてもの}", "{果物|くだもの}", "{食|た}べ{物|もの}", "{飲|の}み{物|もの}"], "That building with the red roof is the library.", "{建物|たてもの} = building."],
    ["26", 2, "{熱|ねつ}がありますから、{今日|きょう}は＿＿に{行|い}きます。", ["{病院|びょういん}", "{銀行|ぎんこう}", "{映画館|えいがかん}", "{喫茶店|きっさてん}"], "I have a fever, so I'm going to the hospital today.", "{病院|びょういん} = hospital."],
    ["27", 2, "{妹|いもうと}は＿＿ですから、まだ{学校|がっこう}に{行|い}きません。", ["{小|ちい}さい", "{高|たか}い", "{長|なが}い", "{新|あたら}しい"], "My little sister is small (young), so she doesn't go to school yet.", "{小|ちい}さい = small."],
    ["28", 2, "{窓|まど}を＿＿と、{涼|すず}しい{風|かぜ}が{入|はい}ります。", ["{開|あ}ける", "{閉|し}める", "{売|う}る", "{立|た}つ"], "If you open the window, a cool breeze comes in.", "{開|あ}ける = to open (something). Opposite: {閉|し}める."],
    ["29", 2, "{雨|あめ}ですから、＿＿を{持|も}って{行|い}きます。", ["{傘|かさ}", "{地図|ちず}", "{切手|きって}", "{辞書|じしょ}"], "It's raining, so I'll take an umbrella.", "{傘|かさ} = umbrella."],
    ["30", 2, "{先生|せんせい}に＿＿をして、{答|こた}えを{教|おし}えてもらいました。", ["{質問|しつもん}", "{旅行|りょこう}", "{散歩|さんぽ}", "{洗濯|せんたく}"], "I asked the teacher a question and had them tell me the answer.", "{質問|しつもん}をする = to ask a question."],
    ["31", 2, "{今日|きょう}は{天気|てんき}が＿＿ですから、{公園|こうえん}で{遊|あそ}びます。", ["いい", "{悪|わる}い", "{暗|くら}い", "{強|つよ}い"], "The weather is nice today, so I'll play in the park.", "いい{天気|てんき} = good weather."],
    ["32", 3, "{私|わたし}は＿＿{朝|あさ}{六時|ろくじ}に{起|お}きます。", ["いつも", "ぜんぜん", "あまり", "どうぞ"], "I always get up at six in the morning.", "いつも = always. ぜんぜん / あまり need a negative."],
    ["33", 3, "{日本語|にほんご}は＿＿{勉強|べんきょう}しましたから、{少|すこ}し{話|はな}せます。", ["{三年|さんねん}", "{三枚|さんまい}", "{三本|さんぼん}", "{三台|さんだい}"], "I studied Japanese for three years, so I can speak a little.", "Years: 〜{年|ねん}. {三年|さんねん} = three years."],
    ["34", 3, "{図書館|としょかん}では＿＿{話|はな}してください。", ["{小|ちい}さい{声|こえ}で", "{大|おお}きい{足|あし}で", "{広|ひろ}い{耳|みみ}で", "{高|たか}い{目|め}で"], "Please speak in a quiet voice in the library.", "{小|ちい}さい{声|こえ} = a quiet (small) voice."]
  ]);
})();
