// N5 starter questions. Markup: {漢字|よみ} renders as furigana. "＿＿" marks the blank.
// d = difficulty (1 easy .. 3 harder), t = "v" vocabulary / "g" grammar.
// c = choices, a = index of the correct choice, en = translation, note = short explanation.
window.QUESTIONS = [
  // ---- Vocabulary ----
  { id: "n5v01", lv: 5, t: "v", d: 1, q: "{毎朝|まいあさ}、＿＿を{飲|の}みます。",
    c: ["{水|みず}", "くつ", "{駅|えき}", "{本|ほん}"], a: 0,
    en: "Every morning I drink water.", note: "{水|みず} = water. 飲みます = to drink." },
  { id: "n5v02", lv: 5, t: "v", d: 1, q: "{電車|でんしゃ}で{会社|かいしゃ}へ＿＿。",
    c: ["{行|い}きます", "{食|た}べます", "{聞|き}きます", "{書|か}きます"], a: 0,
    en: "I go to the office by train.", note: "{行|い}きます = to go. Destination + へ + 行きます." },
  { id: "n5v03", lv: 5, t: "v", d: 1, q: "＿＿が{降|ふ}っていますから、かさを{持|も}っていきましょう。",
    c: ["{雨|あめ}", "{風|かぜ}", "{火|ひ}", "{空|そら}"], a: 0,
    en: "It's raining, so let's take an umbrella.", note: "{雨|あめ}が{降|ふ}る = it rains." },
  { id: "n5v04", lv: 5, t: "v", d: 1, q: "このカレーはとても＿＿です。",
    c: ["おいしい", "いそがしい", "ながい", "ちかい"], a: 0,
    en: "This curry is very delicious.", note: "おいしい = delicious." },
  { id: "n5v05", lv: 5, t: "v", d: 1, q: "＿＿で{切手|きって}を{買|か}います。",
    c: ["{郵便局|ゆうびんきょく}", "{病院|びょういん}", "{銀行|ぎんこう}", "{図書館|としょかん}"], a: 0,
    en: "I buy stamps at the post office.", note: "{郵便局|ゆうびんきょく} = post office." },
  { id: "n5v06", lv: 5, t: "v", d: 2, q: "{病気|びょうき}ですから、＿＿へ{行|い}きます。",
    c: ["{病院|びょういん}", "{学校|がっこう}", "{公園|こうえん}", "{駅|えき}"], a: 0,
    en: "I'm sick, so I'm going to the hospital.", note: "{病院|びょういん} = hospital. {病気|びょうき} = illness." },
  { id: "n5v07", lv: 5, t: "v", d: 2, q: "{今日|きょう}はとても＿＿ですから、コートを{着|き}ます。",
    c: ["{寒|さむ}い", "{暑|あつ}い", "{狭|せま}い", "{重|おも}い"], a: 0,
    en: "It's very cold today, so I'll wear a coat.", note: "{寒|さむ}い = cold (weather). {暑|あつ}い = hot (weather)." },
  { id: "n5v08", lv: 5, t: "v", d: 2, q: "{誕生日|たんじょうび}は＿＿{五日|いつか}です。",
    c: ["{十月|じゅうがつ}", "{十人|じゅうにん}", "{十円|じゅうえん}", "{十本|じゅっぽん}"], a: 0,
    en: "My birthday is October 5th.", note: "Months use 月: {十月|じゅうがつ} = October." },
  { id: "n5v09", lv: 5, t: "v", d: 2, q: "{部屋|へや}を{出|で}るとき、{電気|でんき}を＿＿ください。",
    c: ["{消|け}して", "{洗|あら}って", "{歩|ある}いて", "{泳|およ}いで"], a: 0,
    en: "Please turn off the light when you leave the room.", note: "{電気|でんき}を{消|け}す = turn off the light." },
  { id: "n5v10", lv: 5, t: "v", d: 2, q: "わたしの{家|いえ}は{駅|えき}から＿＿です。",
    c: ["{近|ちか}い", "{古|ふる}い", "{若|わか}い", "{多|おお}い"], a: 0,
    en: "My house is close to the station.", note: "{近|ちか}い = near. Opposite: {遠|とお}い." },
  { id: "n5v11", lv: 5, t: "v", d: 3, q: "レストランで{食|た}べる{前|まえ}に、メニューを＿＿。",
    c: ["{見|み}ます", "{売|う}ります", "{泳|およ}ぎます", "{休|やす}みます"], a: 0,
    en: "Before eating at a restaurant, I look at the menu.", note: "{見|み}る = to see / look at." },
  { id: "n5v12", lv: 5, t: "v", d: 3, q: "{日曜日|にちようび}は＿＿ですから、{会社|かいしゃ}へ{行|い}きません。",
    c: ["{休|やす}み", "{仕事|しごと}", "{勉強|べんきょう}", "{練習|れんしゅう}"], a: 0,
    en: "Sunday is a day off, so I don't go to the office.", note: "{休|やす}み = holiday / day off." },
  { id: "n5v13", lv: 5, t: "v", d: 3, q: "あの{建物|たてもの}は{高|たか}くて＿＿です。",
    c: ["{大|おお}きい", "{少|すく}ない", "{軽|かる}い", "{弱|よわ}い"], a: 0,
    en: "That building is tall and big.", note: "{大|おお}きい = big. Don't confuse with {多|おお}い (many)." },
  { id: "n5v14", lv: 5, t: "v", d: 3, q: "{夜|よる}は{暗|くら}いですから、＿＿をつけます。",
    c: ["{電気|でんき}", "{切手|きって}", "{手紙|てがみ}", "{地図|ちず}"], a: 0,
    en: "It's dark at night, so I turn on the light.", note: "{電気|でんき}をつける = turn on the light." },

  // ---- Grammar ----
  { id: "n5g01", lv: 5, t: "g", d: 1, q: "わたし＿＿{学生|がくせい}です。",
    c: ["は", "を", "に", "で"], a: 0,
    en: "I am a student.", note: "は marks the topic of the sentence (read \"wa\")." },
  { id: "n5g02", lv: 5, t: "g", d: 1, q: "パン＿＿{食|た}べます。",
    c: ["を", "に", "へ", "で"], a: 0,
    en: "I eat bread.", note: "を marks the direct object of the verb." },
  { id: "n5g03", lv: 5, t: "g", d: 1, q: "{学校|がっこう}＿＿{行|い}きます。",
    c: ["へ", "を", "が", "か"], a: 0,
    en: "I go to school.", note: "へ (read \"e\") marks direction/destination." },
  { id: "n5g04", lv: 5, t: "g", d: 1, q: "{七時|しちじ}＿＿{起|お}きます。",
    c: ["に", "で", "を", "が"], a: 0,
    en: "I wake up at seven o'clock.", note: "に marks a specific point in time." },
  { id: "n5g05", lv: 5, t: "g", d: 1, q: "これはわたし＿＿かばんです。",
    c: ["の", "を", "に", "で"], a: 0,
    en: "This is my bag.", note: "の links nouns and shows possession." },
  { id: "n5g06", lv: 5, t: "g", d: 2, q: "{昨日|きのう}は{雨|あめ}＿＿{降|ふ}りました。",
    c: ["が", "を", "へ", "と"], a: 0,
    en: "It rained yesterday.", note: "Weather like {雨|あめ}/{雪|ゆき} takes が with 降る." },
  { id: "n5g07", lv: 5, t: "g", d: 2, q: "{日本語|にほんご}は{難|むずか}しい＿＿、おもしろいです。",
    c: ["ですが", "ですから", "でも", "それから"], a: 0,
    en: "Japanese is difficult, but it's interesting.", note: "〜ですが = \"…, but …\" (contrast within one sentence)." },
  { id: "n5g08", lv: 5, t: "g", d: 2, q: "いっしょに{昼|ひる}ごはんを{食|た}べ＿＿。",
    c: ["ましょう", "ません", "ました", "たい"], a: 0,
    en: "Let's eat lunch together.", note: "Verb stem + ましょう = \"Let's …\"." },
  { id: "n5g09", lv: 5, t: "g", d: 2, q: "{手|て}を{洗|あら}って＿＿、ごはんを{食|た}べます。",
    c: ["から", "まで", "ながら", "ので"], a: 0,
    en: "I wash my hands, and then eat.", note: "て-form + から = \"after doing …\"." },
  { id: "n5g10", lv: 5, t: "g", d: 2, q: "ここで{写真|しゃしん}をとっ＿＿はいけません。",
    c: ["て", "た", "ない", "ます"], a: 0,
    en: "You must not take photos here.", note: "て-form + はいけません = \"must not …\"." },
  { id: "n5g11", lv: 5, t: "g", d: 2, q: "{窓|まど}を{開|あ}け＿＿ください。",
    c: ["て", "た", "ない", "ます"], a: 0,
    en: "Please open the window.", note: "て-form + ください = \"Please …\"." },
  { id: "n5g12", lv: 5, t: "g", d: 3, q: "{部屋|へや}にだれ＿＿いません。",
    c: ["も", "が", "を", "に"], a: 0,
    en: "There is nobody in the room.", note: "{疑問詞|ぎもんし} + も + negative = \"nobody / nothing / nowhere\"." },
  { id: "n5g13", lv: 5, t: "g", d: 3, q: "{東京|とうきょう}は{大阪|おおさか}＿＿{大|おお}きいです。",
    c: ["より", "ほど", "から", "まで"], a: 0,
    en: "Tokyo is bigger than Osaka.", note: "A は B より … = \"A is more … than B\"." },
  { id: "n5g14", lv: 5, t: "g", d: 3, q: "{明日|あした}テストがある＿＿、{今日|きょう}は{勉強|べんきょう}します。",
    c: ["から", "より", "ほど", "だけ"], a: 0,
    en: "I have a test tomorrow, so I'll study today.", note: "〜から (after a plain/polite clause) = \"because …\"." },
  { id: "n5g15", lv: 5, t: "g", d: 3, q: "{友達|ともだち}＿＿{映画|えいが}を{見|み}ました。",
    c: ["と", "が", "は", "を"], a: 0,
    en: "I watched a movie with a friend.", note: "と = \"with\" (a companion)." }
];
