// More hand-written N4 grammar. Row format: [id, difficulty, question, [correct, wrong, wrong, wrong], English, note]
(function () {
  const add = (t, rows) => rows.forEach(([id, d, q, c, en, note]) => window.QUESTIONS.push({ id: "n4" + t + "x" + id, lv: 4, t, d, q, c, a: 0, en, note }));

  add("g", [
    ["01", 2, "{朝|あさ}ごはんを{食|た}べ＿＿、{学校|がっこう}へ{行|い}きました。", ["ずに", "ないに", "なくに", "ずて"], "I went to school without eating breakfast.", "ない-form without ない + ずに = without doing …. (する → せずに)"],
    ["02", 2, "{傘|かさ}を{持|も}た＿＿{出|で}かけました。", ["ないで", "ずで", "なくで", "ないに"], "I went out without taking an umbrella.", "〜ないで = without doing … (same meaning as 〜ずに)."],
    ["03", 2, "{私|わたし}は{友達|ともだち}に{手伝|てつだ}って＿＿です。", ["ほしい", "ほしく", "ほしかっ", "ほしくて"], "I want my friend to help me.", "Someone に + て-form + ほしい = I want someone to …."],
    ["04", 2, "{電話|でんわ}が{鳴|な}った{時|とき}、{私|わたし}はちょうどお{風呂|ふろ}に{入|はい}って＿＿。", ["いました", "います", "いましょう", "いませんでし"], "When the phone rang, I was just taking a bath.", "〜ていた / 〜ていました = was doing … (past progressive)."],
    ["05", 3, "もっと{勉強|べんきょう}すれ＿＿よかったです。", ["ば", "たら", "と", "なら"], "I should have studied more.", "〜ばよかった = I should have … / it would have been good if …."],
    ["06", 2, "{困|こま}った{時|とき}は、{先生|せんせい}に{聞|き}い＿＿いいですよ。", ["たら", "ば", "と", "で"], "When you're in trouble, it's good to ask the teacher.", "た-form + らいい = it would be good to … (suggestion)."],
    ["07", 3, "{先生|せんせい}に{聞|き}いた＿＿、すぐに{教|おし}えてくれました。", ["ところ", "ばかり", "ほど", "まま"], "When I asked the teacher, he told me right away.", "た-form + ところ = when I did …, (and found / and then)."],
    ["08", 3, "{死|し}ぬ＿＿{疲|つか}れました。", ["ほど", "より", "ばかり", "ずつ"], "I was so tired I could die.", "〜ほど = to the extent that …."],
    ["09", 3, "{歩|ある}けない＿＿{疲|つか}れました。", ["くらい", "ごろ", "ずつ", "まで"], "I was so tired I couldn't walk.", "〜くらい / ぐらい = to the extent of …."],
    ["10", 3, "{窓|まど}を{開|あ}けた＿＿{寝|ね}てしまいました。", ["まま", "ばかり", "ところ", "ほど"], "I fell asleep with the window left open.", "た-form + まま = while remaining in that state."],
    ["11", 3, "{忘|わす}れない＿＿に、メモしておきます。", ["うち", "ながら", "ほど", "ばかり"], "I'll write a note before I forget.", "ない-form + うちに = before it changes / while still …."],
    ["12", 3, "{海|うみ}へ{行|い}く＿＿に、{貝|かい}を{拾|ひろ}います。", ["たび", "ばかり", "ほど", "ながら"], "Every time I go to the sea, I pick up shells.", "Dictionary form + たびに = every time …."],
    ["13", 2, "{弟|おとうと}はいつも{新|あたら}しいゲームを{欲|ほ}し＿＿います。", ["がって", "くて", "そうで", "かって"], "My little brother always wants new games.", "い-adjective stem + がる = shows signs of feeling … (for a third person)."],
    ["14", 2, "{子|こ}どもは{外|そと}へ{行|い}き＿＿います。", ["たがって", "たくて", "たいで", "たがり"], "The child wants to go outside.", "Stem + たがる = (a third person) wants to …."],
    ["15", 2, "{雨|あめ}が{降|ふ}り＿＿です。", ["そう", "そうな", "そうに", "そうの"], "It looks like it's going to rain.", "Stem + そうです = looks like it will … (appearance)."],
    ["16", 3, "あの{人|ひと}は{日本人|にほんじん}の＿＿です。", ["よう", "そう", "かも", "ほど"], "That person seems to be Japanese.", "Noun + のようです = seems / looks like …."],
    ["17", 3, "{日本語|にほんご}が{話|はな}せる＿＿、{毎日|まいにち}{練習|れんしゅう}しています。", ["ように", "ながら", "ところ", "ばかり"], "I practice every day so that I can speak Japanese.", "Potential / plain form + ように = so that …."],
    ["18", 2, "{私|わたし}は{時々|ときどき}、{朝|あさ}ごはんを{食|た}べない＿＿があります。", ["こと", "もの", "の", "ところ"], "I sometimes don't eat breakfast.", "Plain form + ことがある = there are times when …."],
    ["19", 2, "どうしたんですか。{頭|あたま}が{痛|いた}い＿＿です。", ["ん", "の", "もの", "こと"], "What's wrong? I have a headache.", "〜んです explains a reason or situation (spoken form of のです)."],
    ["20", 1, "{窓|まど}が{割|わ}れて＿＿ます。", ["い", "あ", "お", "く"], "The window is broken.", "Intransitive verb + ている = a state that resulted from a change."],
    ["21", 3, "{机|つくえ}の{上|うえ}にメモが{書|か}いて＿＿。", ["あります", "います", "おきます", "しまいます"], "A memo has been written on the desk.", "Transitive verb + てある = something has been done (and remains)."],
    ["22", 3, "{先生|せんせい}は{私|わたし}に{作文|さくぶん}を{直|なお}して＿＿。", ["くれました", "もらいました", "あげました", "ほしいです"], "The teacher corrected my composition for me.", "When someone does a favour for me, use てくれる."],
    ["23", 3, "{私|わたし}は{友達|ともだち}に{重|おも}い{荷物|にもつ}を{持|も}って＿＿。", ["あげました", "くれました", "くださいました", "ほしかったです"], "I carried the heavy luggage for my friend.", "When I do a favour for someone else, use てあげる."],
    ["24", 1, "{田中|たなか}さんは「{明日|あした}{来|き}ます」＿＿{言|い}いました。", ["と", "に", "を", "が"], "Mr. Tanaka said, \"I'll come tomorrow.\"", "A quote + と + 言う."],
    ["25", 2, "これは「ラーメン」＿＿{食|た}べ{物|もの}です。", ["という", "と{言|い}いう", "と{言|い}って", "と{言|い}います"], "This is a food called ramen.", "A noun + という + noun = a … called …."],
    ["26", 3, "{日本|にほん}の{文化|ぶんか}＿＿{調|しら}べています。", ["について", "によって", "として", "に対して"], "I'm researching Japanese culture.", "〜について = about / concerning."],
    ["27", 3, "{私|わたし}は{留学生|りゅうがくせい}＿＿{日本|にほん}に{来|き}ました。", ["として", "について", "によって", "に対して"], "I came to Japan as an exchange student.", "〜として = as (a role or capacity)."],
    ["28", 3, "{国|くに}＿＿{習慣|しゅうかん}が{違|ちが}います。", ["によって", "について", "として", "にとって"], "Customs differ depending on the country.", "〜によって = depending on / by means of."],
    ["29", 3, "{私|わたし}＿＿、{家族|かぞく}が{一番|いちばん}{大切|たいせつ}です。", ["にとって", "によって", "について", "に対して"], "For me, my family is the most important.", "〜にとって = for (someone) / from the viewpoint of."],
    ["30", 3, "{客|きゃく}＿＿、{丁寧|ていねい}に{話|はな}します。", ["に対して", "によって", "について", "にとって"], "I speak politely to customers.", "〜に対して = towards / to (a person or thing)."],
    ["31", 3, "{雪|ゆき}が{降|ふ}った＿＿、{電車|でんしゃ}が{遅|おく}れました。", ["ために", "ように", "ながら", "ばかり"], "Because it snowed, the train was delayed.", "Plain past + ために = because (reason for a result)."],
    ["32", 3, "この{店|みせ}は{安|やす}い＿＿、おいしいです。", ["し", "て", "ずに", "ない"], "This shop is cheap, and also tasty.", "Plain form + し = and what's more … (listing reasons or points)."],
    ["33", 2, "{春|はる}になる＿＿、{花|はな}が{咲|さ}きます。", ["と", "ば", "たら", "でも"], "When spring comes, flowers bloom.", "Dictionary form + と = whenever / when … (a natural result)."],
    ["34", 2, "お{金|かね}があれ＿＿、{旅行|りょこう}に{行|い}きます。", ["ば", "ても", "たら", "と"], "If I have money, I'll go on a trip.", "ば-form: ある → あれば."],
    ["35", 2, "{私|わたし}は{母|はは}に{名前|なまえ}を{呼|よ}ば＿＿。", ["れました", "せました", "ました", "しました"], "I was called by my mother.", "Passive of godan verbs: 呼ぶ → 呼ばれる."],
    ["36", 3, "{電車|でんしゃ}で{足|あし}を{踏|ふ}ま＿＿。", ["れました", "せました", "ました", "さされました"], "My foot was stepped on in the train.", "Passive can show that something unpleasant happened to you."],
    ["37", 3, "{先生|せんせい}は{学生|がくせい}に{本|ほん}を{読|よ}ま＿＿。", ["せました", "れました", "ました", "さました"], "The teacher made the students read the book.", "Causative of godan verbs: 読む → 読ませる (make / let someone do)."],
    ["38", 3, "{社長|しゃちょう}は{今|いま}、{会議室|かいぎしつ}に＿＿。", ["いらっしゃいます", "おります", "{参|まい}ります", "{申|もう}します"], "The president is in the meeting room now.", "いらっしゃる = honorific for いる; おる is humble (for yourself)."],
    ["39", 3, "{私|わたし}が{荷物|にもつ}をお{持|も}ち＿＿。", ["します", "になります", "くださいます", "です"], "Let me carry your luggage.", "お + stem + する = humble form (you act for someone else)."],
    ["40", 3, "{先生|せんせい}がこの{本|ほん}を＿＿ました。", ["お{読|よ}みになり", "お{読|よ}みし", "お{読|よ}み", "{読|よ}みいただき"], "The teacher read this book.", "お + stem + になる = honorific form (for the person you respect)."],
    ["41", 2, "もう{遅|おそ}いから、{帰|かえ}ろ＿＿。", ["う", "ます", "よう", "ない"], "It's late, so let's go home.", "Volitional of godan verbs: 帰る → 帰ろう."],
    ["42", 2, "みんなで{食|た}べ＿＿。", ["よう", "ろう", "ます", "ない"], "Let's eat together.", "Volitional of ichidan verbs: drop る + よう."],
    ["43", 3, "いくら{食|た}べ＿＿、{太|ふと}りません。", ["ても", "たら", "ば", "ながら"], "No matter how much I eat, I don't gain weight.", "いくら + て-form + も = no matter how much …."],
    ["44", 3, "どこ＿＿{行|い}けます。", ["でも", "へも", "にも", "しか"], "You can go anywhere.", "Question word + でも = any … at all."],
    ["45", 3, "うちの{子|こ}は{肉|にく}＿＿{食|た}べます。", ["ばかり", "ほど", "ずつ", "ごろ"], "My child eats nothing but meat.", "Noun + ばかり = only / nothing but."],
    ["46", 2, "{毎日|まいにち}、{漢字|かんじ}を{五|いつ}つ＿＿{覚|おぼ}えます。", ["ずつ", "ごろ", "まま", "ながら"], "Every day, I memorize five kanji at a time.", "Amount + ずつ = … each / … at a time."],
    ["47", 3, "この{会社|かいしゃ}では、{毎朝|まいあさ}、{掃除|そうじ}をする＿＿なっています。", ["ことに", "ながら", "ばかり", "ほど"], "At this company, it's the rule to clean every morning.", "〜ことになっている = it's a rule / arrangement that …."],
    ["48", 2, "{家|いえ}に{着|つ}い＿＿、{電話|でんわ}します。", ["たら", "ば", "と", "なら"], "I'll call you once I get home.", "た-form + ら = when / after …."],
    ["49", 3, "{先生|せんせい}に{本|ほん}を{貸|か}して＿＿ました。", ["いただき", "くださり", "ほし", "ちゃい"], "I had the teacher lend me a book.", "〜ていただく = humble way of saying 〜てもらう."],
    ["50", 2, "{私|わたし}は{田中|たなか}さん＿＿{同|おな}じ{大学|だいがく}です。", ["と", "に", "を", "が"], "I go to the same university as Mr. Tanaka.", "A と同じ = the same as A."],
    ["51", 3, "{雪|ゆき}＿＿{白|しろ}いです。", ["のように", "のような", "のよう", "のために"], "It's white like snow.", "Noun + のように + adjective / verb = like …."],
    ["52", 1, "{田中|たなか}さんは{医者|いしゃ}＿＿なりました。", ["に", "が", "を", "で"], "Mr. Tanaka became a doctor.", "Noun + になる = become …."],
    ["53", 1, "コーヒーを{二|に}＿＿ください。", ["{杯|はい}", "{本|ほん}", "{枚|まい}", "{台|だい}"], "Two cups of coffee, please.", "Cups / glasses of a drink: 〜{杯|はい}."],
    ["54", 2, "{本|ほん}を{三|さん}＿＿{借|か}りました。", ["{冊|さつ}", "{枚|まい}", "{台|だい}", "{匹|ひき}"], "I borrowed three books.", "Books and bound volumes: 〜{冊|さつ}."],
    ["55", 2, "{犬|いぬ}を{二|に}＿＿{飼|か}っています。", ["{匹|ひき}", "{台|だい}", "{枚|まい}", "{冊|さつ}"], "I have two dogs.", "Small animals: 〜{匹|ひき} (三匹 is さんびき)."],
    ["56", 3, "A「{紅茶|こうちゃ}とコーヒー、＿＿が{好|す}きですか。」\nB「コーヒーです。」", ["どちら", "どれ", "どこ", "だれ"], "A: Which do you like, tea or coffee? B: Coffee.", "どちら = which (of two)."],
    ["57", 3, "＿＿{雨|あめ}が{降|ふ}ったら、{行|い}きません。", ["もし", "ぜひ", "ぜんぜん", "まだ"], "If it rains, I won't go.", "もし = if (introduces a hypothetical)."],
    ["58", 3, "{明日|あした}は＿＿{雨|あめ}でしょう。", ["たぶん", "ぜんぜん", "あまり", "ぜひ"], "It will probably rain tomorrow.", "たぶん ~ でしょう = probably."],
    ["59", 2, "{試験|しけん}があります。＿＿、{勉強|べんきょう}しています。", ["だから", "しかし", "でも", "ところで"], "I have an exam. So I'm studying.", "だから = therefore / so."],
    ["60", 2, "この{店|みせ}は{安|やす}いです。＿＿、おいしくないです。", ["しかし", "だから", "それで", "ですから"], "This shop is cheap. However, it isn't tasty.", "しかし = however (contrast)."]
  ]);
})();
