// Reading passages. window.READING[level] = [{ id, text (furigana markup), en (translation), qs: [[question, [correct, wrong, wrong, wrong]], ...] }]
// Each question belongs to its passage; the passage is shown above the question.
window.READING = window.READING || {};

window.READING[5] = [
  { id: "p01",
    text: "わたしは{田中|たなか}です。{大学生|だいがくせい}です。{毎日|まいにち}{電車|でんしゃ}で{大学|だいがく}へ{行|い}きます。{大学|だいがく}は{駅|えき}から{歩|ある}いて{五分|ごふん}です。",
    en: "I'm Tanaka. I'm a university student. I go to university by train every day. The university is a five-minute walk from the station.",
    qs: [["How does Tanaka get to university?", ["By train", "By bus", "By bicycle", "By car"]],
         ["How long is the walk from the station to the university?", ["5 minutes", "15 minutes", "50 minutes", "1 hour"]]] },
  { id: "p02",
    text: "{昨日|きのう}は{日曜日|にちようび}でした。{朝|あさ}、{友達|ともだち}と{公園|こうえん}へ{行|い}きました。{天気|てんき}がよかったので、{公園|こうえん}で{弁当|べんとう}を{食|た}べました。{午後|ごご}は{家|いえ}で{本|ほん}を{読|よ}みました。",
    en: "Yesterday was Sunday. In the morning I went to the park with a friend. The weather was nice, so we ate lunch boxes in the park. In the afternoon I read a book at home.",
    qs: [["Where did the writer go in the morning?", ["To the park", "To the library", "To the station", "To school"]],
         ["What did the writer do in the afternoon?", ["Read a book at home", "Ate lunch in the park", "Went shopping", "Watched a movie"]],
         ["Why did they eat in the park?", ["The weather was nice", "It was a birthday", "The restaurant was closed", "They were very hungry"]]] },
  { id: "p03",
    text: "お{知|し}らせ\n{来週|らいしゅう}の{月曜日|げつようび}は{図書館|としょかん}が{休|やす}みです。{火曜日|かようび}から{土曜日|どようび}までは、{九時|くじ}から{五時|ごじ}まで{開|あ}いています。{日曜日|にちようび}も{休|やす}みです。",
    en: "Notice: The library is closed next Monday. From Tuesday to Saturday it is open from 9 to 5. It is also closed on Sunday.",
    qs: [["On which days is the library closed next week?", ["Monday and Sunday", "Saturday and Sunday", "Only Monday", "Tuesday and Sunday"]],
         ["What time does the library open on Tuesday?", ["9:00", "5:00", "10:00", "8:00"]]] },
  { id: "p04",
    text: "{私|わたし}の{好|す}きな{店|みせ}は、{駅|えき}の{近|ちか}くのレストランです。そのレストランのカレーは{安|やす}くて、とてもおいしいです。でも、{昼|ひる}は{人|ひと}がたくさんいますから、{私|わたし}はいつも{夜|よる}に{行|い}きます。",
    en: "My favourite place is a restaurant near the station. The curry there is cheap and very tasty. But at lunchtime there are many people, so I always go at night.",
    qs: [["What does the writer like about the restaurant?", ["The curry is cheap and tasty", "It is very quiet", "It is open all day", "It is close to home"]],
         ["When does the writer go to the restaurant?", ["At night", "At noon", "In the morning", "On Sundays"]]] },
  { id: "p05",
    text: "{明日|あした}は{雨|あめ}です。ですから、{山|やま}には{行|い}きません。{家|いえ}で{映画|えいが}を{見|み}ます。{友達|ともだち}も{来|き}ます。",
    en: "Tomorrow it will rain. So I won't go to the mountains. I'll watch a movie at home. A friend will come too.",
    qs: [["What will the writer do tomorrow?", ["Watch a movie at home", "Climb a mountain", "Go shopping", "Visit a friend's house"]],
         ["Why won't the writer go to the mountains?", ["It will rain", "The writer is tired", "A friend is sick", "It is too far"]]] },
  { id: "p06",
    text: "{私|わたし}の{家族|かぞく}は{四人|よにん}です。{父|ちち}と{母|はは}と{妹|いもうと}と{私|わたし}です。{父|ちち}は{会社員|かいしゃいん}で、{母|はは}は{先生|せんせい}です。{妹|いもうと}は{高校生|こうこうせい}です。",
    en: "There are four people in my family: my father, my mother, my younger sister and me. My father is an office worker and my mother is a teacher. My younger sister is a high school student.",
    qs: [["Who is a teacher?", ["The writer's mother", "The writer's father", "The writer's sister", "The writer"]],
         ["How many people are in the writer's family?", ["Four", "Three", "Five", "Six"]]] },
  { id: "p07",
    text: "{昨日|きのう}、デパートで{新|あたら}しいかばんを{買|か}いました。{赤|あか}いかばんは{五千円|ごせんえん}でした。{黒|くろ}いかばんは{八千円|はっせんえん}でした。{私|わたし}は{赤|あか}いかばんにしました。",
    en: "Yesterday I bought a new bag at the department store. The red bag was 5,000 yen. The black bag was 8,000 yen. I chose the red one.",
    qs: [["How much was the bag the writer bought?", ["5,000 yen", "8,000 yen", "3,000 yen", "13,000 yen"]],
         ["What colour bag did the writer buy?", ["Red", "Black", "Blue", "White"]]] },
  { id: "p08",
    text: "{私|わたし}は{毎朝|まいあさ}{六時|ろくじ}に{起|お}きます。{顔|かお}を{洗|あら}ってから、{朝|あさ}ごはんを{食|た}べます。{七時|しちじ}に{家|いえ}を{出|で}て、{八時|はちじ}に{会社|かいしゃ}に{着|つ}きます。",
    en: "I get up at six every morning. After washing my face, I eat breakfast. I leave home at seven and arrive at the office at eight.",
    qs: [["What time does the writer leave home?", ["7:00", "6:00", "8:00", "9:00"]],
         ["What does the writer do right after washing their face?", ["Eats breakfast", "Leaves home", "Goes to bed", "Reads the news"]]] },
  { id: "p09",
    text: "{田中|たなか}さんへ\n{来週|らいしゅう}の{土曜日|どようび}に、{私|わたし}の{家|いえ}でパーティーをします。{三時|さんじ}から{始|はじ}めます。{飲|の}み{物|もの}は{私|わたし}が{買|か}います。{田中|たなか}さんは、{何|なに}か{食|た}べ{物|もの}を{持|も}ってきてください。\n{山田|やまだ}",
    en: "To Mr. Tanaka: Next Saturday I'm having a party at my house. It starts at 3. I'll buy the drinks. Please bring some food. — Yamada",
    qs: [["What should Tanaka bring?", ["Some food", "Some drinks", "A present", "Nothing"]],
         ["What time does the party start?", ["3:00", "2:00", "4:00", "5:00"]],
         ["Who will buy the drinks?", ["Yamada", "Tanaka", "A friend", "Nobody"]]] },
  { id: "p10",
    text: "うちには{犬|いぬ}が{一匹|いっぴき}とねこが{二匹|にひき}います。{犬|いぬ}の{名前|なまえ}はポチです。ポチは{大|おお}きくて、{元気|げんき}です。ねこは{小|ちい}さくて、{静|しず}かです。",
    en: "At our house there is one dog and two cats. The dog's name is Pochi. Pochi is big and lively. The cats are small and quiet.",
    qs: [["How many cats are there?", ["Two", "One", "Three", "None"]],
         ["What is the dog like?", ["Big and lively", "Small and quiet", "Old and tired", "Young and shy"]]] }
];

window.READING[4] = [
  { id: "p01",
    text: "{山田|やまだ}さんへ\n{明日|あした}の{会議|かいぎ}は{三時|さんじ}からでしたが、{社長|しゃちょう}が{出張|しゅっちょう}から{帰|かえ}るのが{遅|おそ}くなったので、{四時|よじ}からになりました。{場所|ばしょ}は{同|おな}じ{会議室|かいぎしつ}です。{資料|しりょう}は{私|わたし}が{用意|ようい}しておきます。\n{鈴木|すずき}",
    en: "To Mr. Yamada: Tomorrow's meeting was to start at 3, but the president's return from a business trip is delayed, so it will start at 4. The place is the same meeting room. I'll prepare the materials in advance. — Suzuki",
    qs: [["Why was the meeting time changed?", ["The president will return late from a business trip", "The meeting room is being used", "Yamada asked to change it", "It is a national holiday"]],
         ["What will Suzuki do?", ["Prepare the materials", "Book a new room", "Meet the president at the station", "Call Yamada tonight"]],
         ["Where will the meeting be held?", ["In the same meeting room", "In a different room", "At the president's office", "At a restaurant"]]] },
  { id: "p02",
    text: "{先週|せんしゅう}の{日曜日|にちようび}、{初|はじ}めて{富士山|ふじさん}に{登|のぼ}りました。{朝|あさ}{四時|よじ}に{出発|しゅっぱつ}して、{昼|ひる}ごろ{山|やま}の{上|うえ}に{着|つ}きました。{疲|つか}れましたが、{景色|けしき}がとてもきれいで、{登|のぼ}ってよかったと{思|おも}いました。",
    en: "Last Sunday I climbed Mt. Fuji for the first time. I set out at 4 a.m. and reached the top around noon. I was tired, but the view was so beautiful that I was glad I had climbed it.",
    qs: [["When did the writer reach the top?", ["Around noon", "At 4 a.m.", "In the evening", "At midnight"]],
         ["How did the writer feel in the end?", ["Tired, but glad", "Disappointed", "Bored", "Afraid"]]] },
  { id: "p03",
    text: "サクラ{日本語学校|にほんごがっこう}\n{初|はじ}めての{人|ひと}も、{勉強|べんきょう}したことがある{人|ひと}も、{安心|あんしん}して{来|き}てください。クラスは{月曜日|げつようび}から{金曜日|きんようび}まで、{午前|ごぜん}と{午後|ごご}があります。{体験|たいけん}レッスンは{無料|むりょう}です。{予約|よやく}は{電話|でんわ}でお{願|ねが}いします。",
    en: "Sakura Japanese School. Whether you're a beginner or have studied before, come with peace of mind. Classes run Monday to Friday, with morning and afternoon sessions. A trial lesson is free. Please reserve by phone.",
    qs: [["How can you reserve a trial lesson?", ["By phone", "By email", "At the school desk only", "On the website"]],
         ["How much is the trial lesson?", ["Free", "1,000 yen", "5,000 yen", "It isn't mentioned"]],
         ["On which days are classes held?", ["Monday to Friday", "Saturday and Sunday", "Every day", "Only Monday"]]] },
  { id: "p04",
    text: "{私|わたし}は{毎日|まいにち}{自転車|じてんしゃ}で{会社|かいしゃ}に{通|かよ}っています。{電車|でんしゃ}より{時間|じかん}はかかりますが、お{金|かね}がかかりませんし、いい{運動|うんどう}にもなります。ただ、{雨|あめ}の{日|ひ}は{電車|でんしゃ}で{行|い}くことにしています。",
    en: "I commute to work by bicycle every day. It takes longer than the train, but it doesn't cost money and it's good exercise too. However, on rainy days I take the train.",
    qs: [["What is a good point of cycling, according to the writer?", ["It costs nothing and is good exercise", "It is faster than the train", "It is safe in the rain", "It is good for meeting people"]],
         ["What does the writer do on rainy days?", ["Takes the train", "Takes a taxi", "Stays home", "Walks"]]] },
  { id: "p05",
    text: "お{客様|きゃくさま}へ\n{工事|こうじ}のため、{来月|らいげつ}の{十日|とおか}から{十五日|じゅうごにち}まで、{店|みせ}を{休|やす}みます。{十六日|じゅうろくにち}から、いつもの{時間|じかん}に{開|あ}けます。ご{迷惑|めいわく}をおかけしますが、よろしくお{願|ねが}いします。",
    en: "To our customers: Because of construction work, the shop will be closed from the 10th to the 15th of next month. From the 16th we will open at the usual time. We apologise for the inconvenience.",
    qs: [["Why will the shop be closed?", ["Because of construction work", "Because of a holiday", "Because the owner is sick", "Because of a move"]],
         ["When will the shop reopen?", ["On the 16th", "On the 10th", "On the 15th", "On the 1st"]]] },
  { id: "p06",
    text: "{母|はは}は{料理|りょうり}が{上手|じょうず}です。{特|とく}に{魚|さかな}の{料理|りょうり}が{得意|とくい}で、{私|わたし}は{子|こ}どもの{頃|ころ}からそれが{大好|だいす}きでした。{一人|ひとり}で{住|す}むようになってから、{母|はは}に{作|つく}り{方|かた}を{教|おし}えてもらいましたが、{同|おな}じ{味|あじ}にはなりません。",
    en: "My mother is good at cooking. She is especially good at fish dishes, and I have loved them since I was a child. After I started living alone, I had her teach me how to make them, but they don't taste the same.",
    qs: [["What is the writer's mother especially good at?", ["Fish dishes", "Sweets", "Soup", "Salads"]],
         ["What is the writer's problem?", ["The dishes don't taste the same as mother's", "The writer dislikes fish", "The writer has no time to cook", "The writer forgot the recipe"]]] },
  { id: "p07",
    text: "プールの{利用|りよう}について\n・{入|はい}る{前|まえ}に、{体|からだ}をよく{洗|あら}ってください。\n・{走|はし}ってはいけません。\n・{食|た}べ{物|もの}や{飲|の}み{物|もの}を{持|も}ち{込|こ}まないでください。",
    en: "About using the pool: Please wash your body well before getting in. You must not run. Please don't bring in food or drinks.",
    qs: [["What must you do before entering the pool?", ["Wash your body well", "Take a medical check", "Pay in advance", "Wear a swimming cap"]],
         ["Which of these is NOT mentioned as a rule?", ["Wearing a swimming cap", "Washing before entering", "Not running", "Not bringing food or drinks"]]] },
  { id: "p08",
    text: "{田中|たなか}さん、{今日|きょう}の{夜|よる}、みんなで{食事|しょくじ}に{行|い}くことになりました。{場所|ばしょ}は{駅|えき}の{前|まえ}の{居酒屋|いざかや}です。{七時|しちじ}に{集|あつ}まります。{行|い}ける{場合|ばあい}は、{五時|ごじ}までに{連絡|れんらく}してください。",
    en: "Tanaka, it has been decided that everyone will go for a meal tonight. The place is the izakaya in front of the station. We'll gather at 7. If you can go, please contact me by 5.",
    qs: [["By what time should Tanaka reply?", ["5:00", "7:00", "Noon", "Tomorrow morning"]],
         ["Where is the meal?", ["An izakaya in front of the station", "A restaurant at the office", "Tanaka's home", "A hotel"]]] },
  { id: "p09",
    text: "{私|わたし}が{日本語|にほんご}を{勉強|べんきょう}している{理由|りゆう}は、{日本|にほん}のアニメが{好|す}きだからです。{最初|さいしょ}は{字幕|じまく}を{見|み}ていましたが、{今|いま}は{字幕|じまく}がなくても、{少|すこ}し{分|わ}かるようになりました。{将来|しょうらい}は{日本|にほん}で{働|はたら}きたいです。",
    en: "The reason I study Japanese is that I like Japanese anime. At first I watched with subtitles, but now I can understand a little even without them. In the future I want to work in Japan.",
    qs: [["Why does the writer study Japanese?", ["Because the writer likes Japanese anime", "For a job interview", "Because of a Japanese friend", "For school credit"]],
         ["What can the writer do now?", ["Understand a little without subtitles", "Speak perfectly", "Write long essays", "Work in Japan"]]] },
  { id: "p10",
    text: "{今朝|けさ}、{電車|でんしゃ}が{事故|じこ}のために{止|と}まりました。{会社|かいしゃ}に{電話|でんわ}をして、{遅|おく}れると{伝|つた}えました。{結局|けっきょく}、バスに{乗|の}り{換|か}えて、いつもより{一時間|いちじかん}{遅|おそ}く{会社|かいしゃ}に{着|つ}きました。",
    en: "This morning the train stopped because of an accident. I called the office and told them I'd be late. In the end I switched to a bus and arrived an hour later than usual.",
    qs: [["Why was the writer late?", ["The train stopped because of an accident", "The writer overslept", "The bus broke down", "The writer was sick"]],
         ["How late did the writer arrive?", ["One hour", "Ten minutes", "Half an hour", "Three hours"]]] }
];

window.READING[3] = [
  { id: "p01",
    text: "{最近|さいきん}、コンビニは{物|もの}を{売|う}るだけでなく、{荷物|にもつ}を{送|おく}ったり、{税金|ぜいきん}を{払|はら}ったりすることもできるようになった。{便利|べんり}になったと{感|かん}じる{人|ひと}が{多|おお}い{一方|いっぽう}、{働|はたら}く{人|ひと}の{負担|ふたん}が{大|おお}きくなっているという{声|こえ}もある。",
    en: "Recently, convenience stores have become able not only to sell goods but also to send parcels and accept tax payments. While many people feel life has become more convenient, there are also voices saying that the burden on the workers is growing.",
    qs: [["What can convenience stores do now besides selling goods?", ["Send parcels and accept tax payments", "Repair clothes", "Give medical checks", "Teach languages"]],
         ["What concern is mentioned?", ["The burden on the workers is increasing", "Prices are going up", "The stores are too small", "There are too few stores"]]] },
  { id: "p02",
    text: "{読書|どくしょ}の{習慣|しゅうかん}がある{人|ひと}は、ない{人|ひと}に{比|くら}べて、{語彙|ごい}が{豊富|ほうふ}だと{言|い}われている。しかし、{忙|いそが}しくて{本|ほん}を{読|よ}む{時間|じかん}がないという{人|ひと}も{少|すく}なくない。そのような{人|ひと}には、{通勤|つうきん}の{電車|でんしゃ}の{中|なか}で{少|すこ}しずつ{読|よ}むことをすすめたい。",
    en: "It is said that people who have a reading habit have a richer vocabulary than those who don't. However, quite a few people are too busy to have time to read. To such people, I'd like to recommend reading a little at a time on the commuter train.",
    qs: [["What is said about people who read regularly?", ["They have a richer vocabulary", "They are always busy", "They work longer hours", "They sleep less"]],
         ["What does the writer recommend?", ["Reading a little on the commute", "Reading only on weekends", "Buying more books", "Joining a book club"]]] },
  { id: "p03",
    text: "{町|まち}の{清掃|せいそう}ボランティアを{募集|ぼしゅう}します。{毎月|まいつき}{第一日曜日|だいいちにちようび}の{朝|あさ}、{九時|くじ}から{十一時|じゅういちじ}まで、{駅|えき}の{周|まわ}りを{掃除|そうじ}します。{軍手|ぐんて}とごみ{袋|ぶくろ}はこちらで{用意|ようい}しますので、{動|うご}きやすい{服|ふく}で{来|き}てください。{雨|あめ}の{場合|ばあい}は{中止|ちゅうし}です。",
    en: "We are recruiting volunteers to clean the town. On the first Sunday of every month, from 9 to 11 in the morning, we clean around the station. We will prepare work gloves and garbage bags, so please come in clothes that are easy to move in. In case of rain, it is cancelled.",
    qs: [["What should participants wear?", ["Clothes that are easy to move in", "A uniform", "Rain boots", "Formal clothes"]],
         ["What happens if it rains?", ["The activity is cancelled", "It moves indoors", "It is held the next day", "It goes ahead as usual"]],
         ["How long does the activity last?", ["Two hours", "One hour", "Three hours", "All day"]]] },
  { id: "p04",
    text: "{大学|だいがく}に{入|はい}るために、{初|はじ}めて{一人暮|ひとりぐ}らしを{始|はじ}めた。{最初|さいしょ}は{寂|さび}しくてたまらなかったが、{近所|きんじょ}の{人|ひと}が{野菜|やさい}をくれたり、{声|こえ}をかけてくれたりしたおかげで、{少|すこ}しずつ{慣|な}れてきた。{今|いま}では、この{町|まち}が{好|す}きになっている。",
    en: "To enter university, I started living alone for the first time. At first I was unbearably lonely, but thanks to the neighbours who gave me vegetables and spoke to me, I gradually got used to it. Now I have come to like this town.",
    qs: [["Why did the writer start living alone?", ["To enter university", "To start a new job", "Because of a family problem", "To save money"]],
         ["What helped the writer get used to the new life?", ["The kindness of the neighbours", "Making friends at school", "Phone calls from home", "Joining a club"]]] },
  { id: "p05",
    text: "【{旅行|りょこう}のお{知|し}らせ】\n{社員旅行|しゃいんりょこう}は、{十一月|じゅういちがつ}{三日|みっか}から{四日|よっか}までの{一泊二日|いっぱくふつか}です。{場所|ばしょ}は{箱根|はこね}の{温泉|おんせん}で、{朝|あさ}八時に{会社|かいしゃ}の{前|まえ}からバスで{出発|しゅっぱつ}します。{参加|さんか}する{人|ひと}は、{今月|こんげつ}の{二十日|はつか}までに{名前|なまえ}を{申|もう}し{込|こ}んでください。",
    en: "[Trip notice] The company trip is a two-day, one-night trip from November 3 to 4. The destination is a hot spring in Hakone, and we depart by bus from in front of the company at 8 a.m. Those who will take part, please sign up by the 20th of this month.",
    qs: [["How will they travel to Hakone?", ["By bus from in front of the company", "By train from Tokyo station", "By company car", "By plane"]],
         ["By when must people sign up?", ["The 20th of this month", "November 3", "The end of next month", "Tomorrow"]],
         ["How long is the trip?", ["Two days and one night", "One day", "Three days", "Two nights"]]] },
  { id: "p06",
    text: "{地球|ちきゅう}の{気温|きおん}が{上|あ}がり{続|つづ}けていることから、{世界|せかい}のさまざまな{地域|ちいき}で{異常|いじょう}な{天気|てんき}が{増|ふ}えている。{大雨|おおあめ}による{被害|ひがい}がある{一方|いっぽう}で、{雨|あめ}が{降|ふ}らず{農作物|のうさくぶつ}が{育|そだ}たない{地域|ちいき}もある。{私|わたし}たち{一人|ひとり}ひとりが、{電気|でんき}を{節約|せつやく}するなど、{身近|みぢか}なことから{始|はじ}める{必要|ひつよう}がある。",
    en: "Because the earth's temperature keeps rising, abnormal weather is increasing in various parts of the world. While some areas suffer damage from heavy rain, there are also regions where it doesn't rain and crops don't grow. Each of us needs to start with things close at hand, such as saving electricity.",
    qs: [["What is increasing in various parts of the world?", ["Abnormal weather", "Population", "Tourism", "Sea fishing"]],
         ["What does the writer suggest?", ["Starting with small things such as saving electricity", "Moving to colder regions", "Waiting for new technology", "Planting more crops"]]] },
  { id: "p07",
    text: "{営業部|えいぎょうぶ}の{皆様|みなさま}\n{来週|らいしゅう}の{水曜日|すいようび}に{予定|よてい}していた{打|う}ち{合|あ}わせですが、{取引先|とりひきさき}の{都合|つごう}で、{木曜日|もくようび}の{午後|ごご}二時に{変更|へんこう}になりました。{場所|ばしょ}は{変|か}わりません。{都合|つごう}が{悪|わる}い{方|かた}は、{明日|あした}までに{知|し}らせてください。\n{佐藤|さとう}",
    en: "To everyone in the sales department: The meeting planned for next Wednesday has been changed to Thursday at 2 p.m. because of the client's circumstances. The place does not change. Those who cannot make it, please let me know by tomorrow. — Sato",
    qs: [["Why was the meeting rescheduled?", ["Because of the client's circumstances", "Because of a holiday", "Because Sato is on a trip", "Because the room is full"]],
         ["What should people who can't attend do?", ["Tell Sato by tomorrow", "Send a replacement", "Come late", "Do nothing"]],
         ["What is the new time of the meeting?", ["Thursday at 2 p.m.", "Wednesday at 2 p.m.", "Thursday at 12 noon", "Friday at 2 p.m."]]] },
  { id: "p08",
    text: "{朝|あさ}は{晴|は}れていたので、{傘|かさ}を{持|も}たずに{出|で}かけた。ところが、{帰|かえ}りに{急|きゅう}に{雨|あめ}が{降|ふ}り{出|だ}した。{駅|えき}で{困|こま}っていると、{知|し}らない{女性|じょせい}が「よかったら、どうぞ」と{傘|かさ}を{貸|か}してくれた。{名前|なまえ}を{聞|き}く{前|まえ}に、{彼女|かのじょ}は{行|い}ってしまった。",
    en: "It was sunny in the morning, so I went out without an umbrella. But on the way home it suddenly started to rain. While I was in trouble at the station, a woman I didn't know lent me an umbrella, saying, \"Please, if you like.\" Before I could ask her name, she had gone.",
    qs: [["Why did the writer leave without an umbrella?", ["It was sunny in the morning", "The writer forgot it", "The umbrella was broken", "The writer doesn't like umbrellas"]],
         ["What happened at the station?", ["A stranger lent the writer an umbrella", "The train was delayed", "The writer met an old friend", "The writer bought an umbrella"]],
         ["What could the writer not do?", ["Ask the woman's name", "Go home", "Say thank you to the station staff", "Return the umbrella the same day"]]] }
];
