#!/usr/bin/env python3
"""Builds js/data-vocab-nX.js from the open JLPT word lists (github.com/elzup/jlpt-word-list, MIT;
word data originally from tanos.co.uk, CC BY - Jonathan Waller).
Usage: python3 tools/gen_vocab.py 5 4      (levels to generate)"""
import csv, io, json, re, sys, urllib.request

KANA = re.compile(r"^[ぁ-ゖァ-ヺーー]+$")
HAN = re.compile(r"[一-鿿]")
TAGS = re.compile(r"\s*\((?:v[0-9a-z.,]*|n|adj[a-z-]*|adv|exp|prt|vs|vt|vi|uk|col|pol|hon|hum)\)", re.I)

def clean_meaning(m):
    m = re.sub(r"\([^)]*in reference[^)]*\)", "", m)          # drop wordy usage notes
    senses = [TAGS.sub("", x).strip(" ,") for x in m.split(";") if x.strip()]
    senses = [x for x in senses if x]
    if not senses: return ""
    out = senses[0]
    if len(senses) > 1 and len(out) + len(senses[1]) < 44:
        out += "; " + senses[1]
    if len(out) > 48 and "," in out:
        out = out.split(",")[0].strip()
    return out

def build(level):
    url = "https://raw.githubusercontent.com/elzup/jlpt-word-list/master/src/n%d.csv" % level
    raw = urllib.request.urlopen(url, timeout=60).read().decode("utf8")
    out, seen = [], set()
    for row in csv.reader(io.StringIO(raw)):
        if len(row) < 3: continue
        kanji, kana, meaning = row[0].strip(), row[1].strip(), clean_meaning(row[2])
        if not kana or not meaning or not KANA.match(kana): continue
        if re.search(r"[～〜…()（）/・\s]", kanji) or len(meaning) > 60: continue
        key = (kanji, kana)
        if key in seen: continue
        seen.add(key)
        out.append([kanji, kana, meaning])
    return out

for lv in map(int, sys.argv[1:] or [5, 4]):
    words = build(lv)
    with open("js/data-vocab-n%d.js" % lv, "w", encoding="utf8") as f:
        f.write("// Generated by tools/gen_vocab.py - [word, reading, meaning]. Source: elzup/jlpt-word-list (MIT), data from tanos.co.uk (CC BY).\n")
        f.write("window.VOCAB = window.VOCAB || {};\nwindow.VOCAB[%d] = [\n" % lv)
        f.write(",\n".join(json.dumps(w, ensure_ascii=False) for w in words))
        f.write("\n];\n")
    print("N%d: %d words, %d with kanji" % (lv, len(words), sum(1 for w in words if HAN.search(w[0]))))
