#!/usr/bin/env python3
"""Regenerates js/pokemon.js (names, legendaries, evolution pairs) from the PokeAPI data repo.
Usage: python3 tools/gen_pokemon.py [max_id]   (default 386 = Kanto + Johto + Hoenn)
Sprites are fetched separately (see README)."""
import json, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor

MAX = int(sys.argv[1]) if len(sys.argv) > 1 else 386
# Regions by Pokédex number: Kanto, Johto, Hoenn, Sinnoh, Unova
RANGES = [r for r in ([1, 151], [152, 251], [252, 386], [387, 493], [494, 649]) if r[0] <= MAX]
BASE = "https://raw.githubusercontent.com/PokeAPI/api-data/master/data/api/v2/pokemon-species/%d/index.json"

def fetch(i):
    for _ in range(4):
        try:
            with urllib.request.urlopen(BASE % i, timeout=30) as r:
                return i, json.load(r)
        except Exception:
            pass
    raise SystemExit("failed to fetch species %d" % i)

with ThreadPoolExecutor(12) as ex:
    data = dict(ex.map(fetch, range(1, MAX + 1)))

def sid(url):
    return int(url.rstrip("/").split("/")[-1])

names, legend, baby, pairs = [], [], [], []
for i in range(1, MAX + 1):
    d = data[i]
    names.append(next(n["name"] for n in d["names"] if n["language"]["name"] == "en"))
    if d["is_legendary"] or d["is_mythical"]: legend.append(i)
    if d["is_baby"]: baby.append(i)
    if d["evolves_from_species"]:
        p = sid(d["evolves_from_species"]["url"])
        if p <= MAX: pairs.append([p, i])
pairs.sort()

with open("js/pokemon.js", "w", encoding="utf8") as f:
    f.write("// Generated by tools/gen_pokemon.py from PokeAPI data. Do not edit by hand.\n")
    f.write("window.POKEMON = %s;\n" % json.dumps(names, ensure_ascii=False))
    f.write("// Regions by Pokédex number: Kanto (Gen 1), Johto (Gen 2), Hoenn (Gen 3).\n")
    f.write("window.GEN_RANGES = %s;\n" % json.dumps(RANGES))
    f.write("window.LEGENDARY = %s;\n" % json.dumps(legend))
    f.write("window.BABY = %s;\n" % json.dumps(baby))
    f.write("window.EVO_PAIRS = %s;\n" % json.dumps(pairs))
    f.write('window.spriteUrl = (id, shiny) => "img/pokemon/" + (shiny ? "shiny/" : "") + id + ".png"; // sprites: PokeAPI/sprites\n')
print(len(names), "pokemon;", len(legend), "legendary;", len(baby), "baby;", len(pairs), "evolution pairs")
